const $=selector=>document.querySelector(selector);const $$=selector=>[...document.querySelectorAll(selector)];
let state;let selectedMatch=null;let selectedKiller=null;let selectedPerks=[];let perkLocks=[false,false,false,false];let perkCatalog=[];let perkSpinning=false;let activeRandomizerTab="killer";let perkFilterQuery="";let wheelRotation=0;let wheelSpinning=false;let toastTimer;let perkRequestToken=0;let lastDetailRequest=null;let activeRole="all";let characterRole="all";let characterTimeframe="all-time";let historyRole="all";
const perkNameAliases={
  Dying_Light:"Угасающий свет",DyingLight:"Угасающий свет",DecisiveStrike:"Решающий удар",ObjectOfObsession:"Объект одержимости",
  "Смотри, они бегут":"Поиграть со своей жертвой","Пусть ждут":"Оставьте лучшее напоследок","Истребление слабых":"Угасающий свет",
  "Все средства хороши":"Мертвая хватка","Порча: шут судьбы":"Порча: игрушка","Секущий крюк: сочащиеся раны":"Секущий крюк: дар боли","Секущий крюк «Пучина ярости»":"Секущий крюк: пучина ярости"
};
const perkDisplayName=perk=>perkNameAliases[String(perk?.id||"")]||perkNameAliases[String(perk?.name||"")]||String(perk?.name||"Пусто");
const localizedPerk=perk=>perk?{...perk,name:perkDisplayName(perk)}:perk;
const isRealKillerPerk=perk=>{const name=perkDisplayName(perk).trim().toLocaleLowerCase("ru-RU").replace(/ё/g,"е");return Boolean(name)&&!["навыки убийц","навыки убийцы","умения убийц","умения убийцы"].includes(name)&&!/\(класс\)$/.test(name)};
const portraitFogStates=new WeakMap();
function fogWave(position,time,seed){return Math.sin(position*.082+time*.68+seed)*.5+Math.sin(position*.037-time*.46+seed*1.8)*.31+Math.sin(position*.151+time*.29+seed*.61)*.19}
function drawFogBand(ctx,width,height,side,time,seed,layer){const vertical=side==="left"||side==="right",length=vertical?height:width,cross=vertical?width:height,base=[.145,.112,.083][layer],variance=[.028,.023,.018][layer],alpha=[.2,.16,.12][layer]*(side==="top"?.72:side==="bottom"?.88:1),depthAt=position=>cross*Math.max(.045,base+fogWave(position,time,seed+layer*2.4)*variance);ctx.beginPath();if(side==="left"){ctx.moveTo(0,0);ctx.lineTo(0,height);for(let p=length;p>=0;p-=3)ctx.lineTo(depthAt(p),p)}else if(side==="right"){ctx.moveTo(width,0);ctx.lineTo(width,height);for(let p=length;p>=0;p-=3)ctx.lineTo(width-depthAt(p),p)}else if(side==="top"){ctx.moveTo(0,0);ctx.lineTo(width,0);for(let p=length;p>=0;p-=3)ctx.lineTo(p,depthAt(p))}else{ctx.moveTo(0,height);ctx.lineTo(width,height);for(let p=length;p>=0;p-=3)ctx.lineTo(p,height-depthAt(p))}ctx.closePath();const fade=Math.min(cross*.22,Math.max(...[.145,.112,.083])*cross*1.55),gradient=side==="left"?ctx.createLinearGradient(0,0,fade,0):side==="right"?ctx.createLinearGradient(width,0,width-fade,0):side==="top"?ctx.createLinearGradient(0,0,0,fade):ctx.createLinearGradient(0,height,0,height-fade);gradient.addColorStop(0,`rgba(229,232,231,${alpha})`);gradient.addColorStop(.26,`rgba(201,206,205,${alpha*.72})`);gradient.addColorStop(.56,`rgba(168,175,176,${alpha*.31})`);gradient.addColorStop(.82,`rgba(144,152,154,${alpha*.08})`);gradient.addColorStop(1,"rgba(128,136,139,0)");ctx.fillStyle=gradient;ctx.fill()}
function drawPortraitFog(fog,now){const {canvas,ctx,seed}=fog,width=canvas.width,height=canvas.height,time=now/1000;ctx.clearRect(0,0,width,height);ctx.save();for(let layer=0;layer<3;layer++){drawFogBand(ctx,width,height,"left",time,seed,layer);drawFogBand(ctx,width,height,"right",time,seed+5.2,layer);drawFogBand(ctx,width,height,"bottom",time,seed+9.1,layer);drawFogBand(ctx,width,height,"top",time,seed+13.4,layer)}ctx.globalCompositeOperation="screen";for(let i=0;i<6;i++){const right=i%2===1,cy=((i+.4)*height/6+Math.sin(time*.54+i*1.7)*8+height)%height,cx=right?width:0,radius=width*(.105+(i%3)*.014),gradient=ctx.createRadialGradient(cx,cy,0,cx,cy,radius);gradient.addColorStop(0,"rgba(235,237,235,.075)");gradient.addColorStop(.48,"rgba(187,193,192,.035)");gradient.addColorStop(1,"rgba(147,154,157,0)");ctx.fillStyle=gradient;ctx.fillRect(right?width-radius:0,cy-radius,radius,radius*2)}ctx.restore()}
function setPortraitFogActive(portrait,active){if(!portrait)return;let fog=portraitFogStates.get(portrait);if(!fog){const canvas=portrait.querySelector(".portrait-fog-canvas");if(!canvas)return;fog={canvas,ctx:canvas.getContext("2d",{alpha:true}),seed:Math.random()*20,running:false,lastPaint:0};portraitFogStates.set(portrait,fog)}fog.active=Boolean(active);if(!fog.active){fog.ctx.clearRect(0,0,fog.canvas.width,fog.canvas.height);fog.running=false;return}if(fog.running)return;fog.running=true;const frame=now=>{if(!fog.active||document.hidden||!portrait.isConnected||!portrait.closest(".modal.open")){fog.running=false;return}if(now-fog.lastPaint>=50){fog.lastPaint=now;drawPortraitFog(fog,now)}requestAnimationFrame(frame)};requestAnimationFrame(frame)}
const esc=value=>String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const initials=value=>String(value||"?").split(/\s+/).map(w=>w[0]).join("").slice(0,2).toUpperCase();
const dateText=seconds=>new Intl.DateTimeFormat("ru-RU",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(seconds*1000));
const durationText=seconds=>`${Math.floor((seconds||0)/60)}:${String(Math.floor(seconds||0)%60).padStart(2,"0")}`;
const percentText=value=>`${(Number(value||0)*100).toLocaleString("ru-RU",{minimumFractionDigits:2,maximumFractionDigits:2})}%`;
const hoursText=value=>`${Number(value||0).toLocaleString("ru-RU",{minimumFractionDigits:Number(value||0)%1?1:0,maximumFractionDigits:1})} ч`;
const numberText=value=>Number(value||0).toLocaleString("ru-RU",{maximumFractionDigits:2});
const officialDateText=value=>{if(!value)return"";const numeric=Number(value),date=new Date(Number.isFinite(numeric)&&numeric>0&&numeric<1e12?numeric*1000:value);return Number.isNaN(date.getTime())?"":date.toLocaleDateString("ru-RU")};
const gameTypeText=value=>/^online$/i.test(String(value||""))?"Обычный матч":value||"Обычный матч";
const gameTypeBadge=match=>`<span class="match-mode" title="Режим матча">${esc(gameTypeText(match?.gameType))}</span>`;
const isTwoVsEight=match=>/(?:^|\D)2\s*(?:v|vs|x|х|на|против)\s*8(?:\D|$)|2v8|2vs8|2x8|2х8|calamari/i.test(String(match?.gameType||""));
function survivorCapacity(match){
  const actual=[match?.player,...(match?.participants||[])].filter(person=>person?.role==="survivor").length;
  const modeLimit=isTwoVsEight(match)?8:4;
  return Math.max(actual,modeLimit);
}
const pointText=p=>p?`x ${p.x}, y ${p.y}`:"не задано";
const escapedResult=value=>/escape|escaped|hatch|gate|сбеж/i.test(value||"");
const surrenderResult=value=>/surrender|сдался|покинул матч(?: \(поражение\))?/i.test(value||"");
const disconnectedResult=value=>/disconnect|потеря соединения/i.test(value||"");
const manuallyLeftResult=value=>/manuallyleft|вышел из матча/i.test(value||"");
const resultClass=value=>surrenderResult(value)?"surrender":disconnectedResult(value)?"disconnected":manuallyLeftResult(value)?"manually-left":"";
const resultText=value=>surrenderResult(value)?"СДАЛСЯ (ПОРАЖЕНИЕ)":disconnectedResult(value)?"ПОТЕРЯ СОЕДИНЕНИЯ":manuallyLeftResult(value)?"ВЫШЕЛ ИЗ МАТЧА":String(value||"");
const legacyKillerLabel=String.fromCharCode(1084,1072,1085,1100,1103,1082);
const participantLabel=(person,index)=>person?.role==="killer"&&String(person?.nickname||"").toLocaleLowerCase("ru-RU")===legacyKillerLabel?"Убийца":person?.nickname||(person?.role==="killer"?"Убийца":`Выживший ${index+1}`);

function showToast(message,type="info"){clearTimeout(toastTimer);const el=$("#toast");el.textContent=message;el.className=`toast show ${type}`;toastTimer=setTimeout(()=>el.className="toast",3600)}
function imageOrInitial(image,name){return image?`<img src="${esc(image)}" alt="${esc(name)}" onerror="this.parentElement.classList.add('image-missing');this.remove()">`:`<span class="portrait-placeholder">◇</span>`}
function perkHtml(perk){const name=perkDisplayName(perk),id=perk?.id||"";return `<button type="button" class="perk" title="${esc(name)}" aria-label="Открыть описание: ${esc(name)}" data-perk-id="${esc(id)}" data-perk-name="${esc(name)}" data-perk-image="${esc(perk?.image||"")}">${perk?.image?`<img src="${esc(perk.image)}" alt="${esc(name)}">`:`<span>◇</span>`}</button>`}
function equipmentSlot(item,kind,label,owner=""){const name=item?.name||label,title=item?`${label}: ${name}`:`${label}: пусто`;return `<button type="button" class="equipment-slot ${kind} ${item?"":"empty"}" title="${esc(title)}" aria-label="${esc(title)}" ${item?`data-detail-id="${esc(item.id||"")}" data-detail-name="${esc(name)}" data-detail-image="${esc(item.image||"")}" data-detail-kind="${esc(label)}" data-detail-owner="${esc(owner)}"`:"disabled"}>${item?.image?`<img src="${esc(item.image)}" alt="${esc(name)}" onerror="this.parentElement.classList.add('empty');this.parentElement.innerHTML='<span>+</span>'">`:`<span>+</span>`}</button>`}
function loadoutHtml(person,match=null){const owner=person.character?.name||"";if(isTwoVsEight(match)){return `<div class="score-loadout score-class-loadout">${equipmentSlot(person.characterClass,"character-class","Класс 2 на 8",owner)}${person.characterClass?`<span class="score-class-name">${esc(person.characterClass.name)}</span>`:`<span class="score-class-missing">Класс не сохранён</span>`}</div>`}const addOns=(person.addOns||[]).slice(0,2);return `<div class="score-loadout"><div class="perk-row score-perks">${(person.perks||[]).slice(0,4).map(perkHtml).join("")}</div><i class="loadout-separator"></i><div class="equipment-group item-group">${equipmentSlot(person.power,"item-power",person.role==="killer"?"Сила":"Предмет",owner)}</div><div class="equipment-group addon-group">${equipmentSlot(addOns[0],"addon","Аддон 1",owner)}${equipmentSlot(addOns[1],"addon","Аддон 2",owner)}</div><i class="loadout-separator"></i><div class="equipment-group offering-group">${equipmentSlot(person.offering,"offering","Подношение",owner)}</div></div>`}

function renderRecentChart(){const cutoff=Math.floor(Date.now()/1000)-30*24*60*60,matches=[...roleMatches()].filter(match=>Number(match.startTime||0)>=cutoff).sort((a,b)=>a.startTime-b.startTime),chart=$("#sparkline"),tooltip=$("#chartTooltip"),roleLabel=activeRole==="killer"?"Убийцы":activeRole==="survivor"?"Выжившие":"Убийцы и выжившие",summary=`${roleLabel}: ${matches.length} ${matches.length%10===1&&matches.length%100!==11?"матч":matches.length%10>=2&&matches.length%10<=4&&(matches.length%100<10||matches.length%100>=20)?"матча":"матчей"} за последние 30 дней`;$("#chartPeriodLabel").textContent=`${roleLabel} за 30 дней`;chart.classList.toggle("dense",matches.length>18);chart.classList.toggle("very-dense",matches.length>40);chart.style.setProperty("--chart-gap",matches.length>60?"0px":matches.length>30?"1px":matches.length>18?"2px":"4px");if(!matches.length){chart.innerHTML="<span class=chart-empty>Нет матчей</span>";tooltip.textContent=`${roleLabel}: за последние 30 дней матчей в архиве нет.`;return}chart.innerHTML=matches.map((match,index)=>{const killer=match.player?.role==="killer",capacity=survivorCapacity(match),success=killer?Math.max(0,Math.min(1,Number(match.kills||0)/capacity)):(escapedResult(match.player?.result)?1:.12),result=killer?`${match.kills??0} из ${capacity} убийств`:(surrenderResult(match.player?.result)?"Сдался (поражение)":disconnectedResult(match.player?.result)?"Потеря соединения":manuallyLeftResult(match.player?.result)?"Вышел из матча":escapedResult(match.player?.result)?"Побег":"Не удалось сбежать"),label=`${match.player?.character?.name||"Персонаж"}: ${result}`;return `<button class="result-bar role-${killer?"killer":"survivor"}" data-chart-match="${esc(match.id)}" data-chart-label="${esc(label)}" data-chart-meta="${esc(`${dateText(match.startTime)} · ${match.map} · ${gameTypeText(match.gameType)}`)}" style="--bar-height:${Math.max(10,Math.round(success*100))}%" aria-label="${esc(label)}"><i style="animation-delay:${Math.min(index,30)*18}ms"></i></button>`}).join("");tooltip.textContent=summary;$$('[data-chart-match]').forEach(button=>{button.onmouseenter=button.onfocus=()=>{tooltip.innerHTML=`<b>${esc(button.dataset.chartLabel)}</b><br>${esc(button.dataset.chartMeta)}`};button.onmouseleave=button.onblur=()=>{tooltip.textContent=summary};button.onclick=()=>openMatch(button.dataset.chartMatch)})}

function roleMatches(role=activeRole){const matches=state.matches||[];return role==="all"?matches:matches.filter(m=>m.player?.role===role)}
function stats(role=activeRole,sourceMatches=null){const matches=sourceMatches||roleMatches(role),killerMatches=matches.filter(m=>m.player?.role==="killer"),survivorMatches=matches.filter(m=>m.player?.role==="survivor"),totalKills=killerMatches.reduce((s,m)=>s+(Number.isFinite(m.kills)?m.kills:0),0),possibleKills=killerMatches.reduce((s,m)=>s+survivorCapacity(m),0),escapes=survivorMatches.filter(m=>escapedResult(m.player?.result)).length,avg=killerMatches.length?totalKills/killerMatches.length:0,completeWins=killerMatches.filter(m=>m.kills===survivorCapacity(m)).length,avgScore=matches.length?matches.reduce((s,m)=>s+Number(m.player?.score||0),0)/matches.length:0,chars={};matches.forEach(m=>{const n=m.player?.character?.name||"Неизвестно";chars[n]=(chars[n]||0)+1});const favorite=Object.entries(chars).sort((a,b)=>b[1]-a[1])[0]?.[0]||"—";return{matches:matches.length,killerMatches:killerMatches.length,survivorMatches:survivorMatches.length,totalKills,possibleKills,escapes,avg,completeWins,avgScore,favorite,killRate:possibleKills?Math.round(totalKills/possibleKills*100):0,escapeRate:survivorMatches.length?Math.round(escapes/survivorMatches.length*100):0}}

function renderProfile(){const profile=state.account||{},name=profile.name||"Вход не выполнен",initial=initials(name).slice(0,1)||"?",avatar=profile.avatar||"";$("#navProfileName").textContent=name;$("#profileName").textContent=name;$("#navProfilePlatform").textContent=profile.provider?.toUpperCase()||"FOG COMPANION";[$("#navAvatarInitial"),$("#profileAvatarInitial")].forEach(el=>el.textContent=initial);[$("#navAvatarImage"),$("#profileAvatarImage")].forEach(img=>{img.onerror=()=>{img.removeAttribute("src");img.classList.remove("loaded")};if(avatar){img.src=avatar;img.classList.add("loaded")}else{img.removeAttribute("src");img.classList.remove("loaded")}});$("#authGate").classList.toggle("hidden",Boolean(state.account));$("#accountStatus").textContent=state.account?`${name} · SteamID ${profile.steamId}`:"Steam не подключён";$("#steamAccountButton").textContent=state.account?"Переподключить Steam":"Войти через Steam";$("#accountLogoutButton").hidden=!state.account}

function renderSummary(){const s=stats();let cards,profileRate,profileLabel,eyebrow;if(activeRole==="killer"){cards=[["МАТЧЕЙ ЗА УБИЙЦУ",s.matches,"в локальном архиве"],["УБИЙСТВ",s.totalKills,`${s.killRate}% от возможных`],["СРЕДНЕЕ ЗА МАТЧ",s.avg.toFixed(1),"за один матч"],["ПОЛНЫХ ПОБЕД",s.completeWins,"убиты все выжившие матча"]];profileRate=s.avg.toFixed(1);profileLabel="Среднее убийств";eyebrow="ПРОФИЛЬ УБИЙЦЫ"}else if(activeRole==="survivor"){cards=[["МАТЧЕЙ ЗА ВЫЖИВШЕГО",s.matches,"в локальном архиве"],["ПОБЕГОВ",s.escapes,`${s.escapeRate}% успешных матчей`],["ПРОЦЕНТ ПОБЕГОВ",`${s.escapeRate}%`,"ворота или люк"],["СРЕДНИЕ ОЧКИ",Math.round(s.avgScore).toLocaleString("ru-RU"),"за один матч"]];profileRate=`${s.escapeRate}%`;profileLabel="Процент побегов";eyebrow="ПРОФИЛЬ ВЫЖИВШЕГО"}else{cards=[["ВСЕГО МАТЧЕЙ",s.matches,`${s.killerMatches} убийца · ${s.survivorMatches} выживший`],["УБИЙСТВ",s.totalKills,`${s.killRate}% за убийцу`],["ПОБЕГОВ",s.escapes,`${s.escapeRate}% за выжившего`],["СРЕДНИЕ ОЧКИ",Math.round(s.avgScore).toLocaleString("ru-RU"),"за один матч"]];profileRate=`${s.killRate}% / ${s.escapeRate}%`;profileLabel="Убийства / побеги";eyebrow="ОБЩИЙ ПРОФИЛЬ"}$("#summaryCards").innerHTML=cards.map(([l,v,h])=>`<article class="summary-card"><span>${l}</span><b>${v}</b><small>${h}</small></article>`).join("");
$("#profileMatches").textContent=s.matches;$("#profileAverage").textContent=profileRate;$("#profileRateLabel").textContent=profileLabel;$("#profileFavorite").textContent=s.favorite;$("#overviewRoleEyebrow").textContent=eyebrow;$("#profileRoleLabel").textContent=activeRole==="killer"?"Профиль убийцы":activeRole==="survivor"?"Профиль выжившего":"Общий профиль";
$("#demoBadge").classList.toggle("hidden",!state.meta?.demo);$("#lastSyncLabel").textContent=state.meta?.lastSync?`Последняя синхронизация: ${new Date(state.meta.lastSync).toLocaleString("ru-RU")}`:"Еще не синхронизировано";
const behaviourAuthenticated=Boolean(state.meta?.behaviourAuthenticated);$("#syncSideButton").textContent=behaviourAuthenticated?"Синхронизировать":"Войти в аккаунт";$("#behaviourLogoutButton").hidden=!behaviourAuthenticated;
renderRecentChart();
const cutoff30Days=Math.floor(Date.now()/1000)-30*24*60*60,recent=stats("all",(state.matches||[]).filter(match=>Number(match.startTime||0)>=cutoff30Days)),efficiency=[["Процент убийств",recent.killRate],["Процент побегов",recent.escapeRate]];$("#efficiencyRows").innerHTML=efficiency.map(([n,v])=>`<div class="efficiency-row"><div><span>${n}</span><b>${v}%</b></div><div class="bar"><i style="width:${v}%"></i></div></div>`).join("");
}

function mapPreview(match){return `<div class="map-preview ${match.mapImage?"":"no-image"}" title="${esc(match.map||"Неизвестная карта")}">${match.mapImage?`<img src="${esc(match.mapImage)}" alt="${esc(match.map||"Карта")}" loading="lazy" onerror="this.parentElement.classList.add('no-image');this.remove()">`:""}<span>${esc(match.map||"Неизвестная карта")}</span></div>`}
function twoVsEightMapPreview(match){return `<div class="two-v-eight-map">${mapPreview(match)}<div class="two-v-eight-map-timing"><b>${durationText(match.duration)}</b><span>${dateText(match.startTime)}</span></div><div class="two-v-eight-map-compact"><b>${esc(match.map||"Неизвестная карта")}</b><span>${durationText(match.duration)} · ${dateText(match.startTime)}</span></div></div>`}
function matchClassHtml(person){const item=person?.characterClass;if(!item)return`<span class="match-class-missing">Класс не сохранён</span>`;return `<button type="button" class="match-character-class" title="Класс 2 на 8: ${esc(item.name)}" data-detail-id="${esc(item.id||"")}" data-detail-name="${esc(item.name)}" data-detail-image="${esc(item.image||"")}" data-detail-kind="Класс 2 на 8" data-detail-owner="${esc(person.character?.name||"")}">${item.image?`<img src="${esc(item.image)}" alt="${esc(item.name)}">`:""}<span>${esc(item.name)}</span></button>`}
function survivorStackHtml(survivors,capacity){const slots=survivors.slice(0,capacity);while(slots.length<capacity)slots.push(null);return slots.map(s=>s?`<div class="survivor" title="${esc(s.nickname)} · ${esc(s.character?.name)} · ${esc(resultText(s.result))}">${imageOrInitial(s.character?.image,s.character?.name)}<i class="${resultClass(s.result)||(escapedResult(s.result)?"escaped":"")}"></i></div>`:`<div class="survivor survivor-empty" title="Источник не сохранил данные этого игрока"><span>?</span></div>`).join("")}
function matchCard(match){const p=match.player||{},twoVsEight=isTwoVsEight(match),survivors=[p,...(match.participants||[])].filter(x=>x.role==="survivor"),visibleSurvivors=twoVsEight?survivors.slice(0,8):survivors.slice(0,4),perks=(p.perks||[]).slice(0,4),supportingLoadout=twoVsEight?matchClassHtml(p):perks.map(perkHtml).join("");return `<article class="match-card role-${p.role||"unknown"} ${twoVsEight?"is-two-v-eight":""}" data-match="${esc(match.id)}">
  <div class="killer-identity"><div class="portrait">${imageOrInitial(p.character?.image,p.character?.name)}</div><div><b>${esc(p.character?.name||"Неизвестно")}</b><small>${p.role==="killer"?"УБИЙЦА":"ВЫЖИВШИЙ"}</small></div></div>
  <div class="match-mode-cell">${gameTypeBadge(match)}</div>
  <div class="match-main"><div class="result-line"><span class="result-pill ${resultClass(p.result)}">${esc(resultText(p.result)||`${match.kills??"?"} убийства`)}</span>${twoVsEight?"":`<span class="match-meta"><b>${esc(match.map)} · ${durationText(match.duration)}</b><small>${dateText(match.startTime)}</small></span>`}</div><div class="perk-row ${twoVsEight?"two-v-eight-class-row":""}">${supportingLoadout}</div></div>
  ${twoVsEight?twoVsEightMapPreview(match):mapPreview(match)}
  <div class="survivor-stack">${survivorStackHtml(visibleSurvivors,twoVsEight?8:visibleSurvivors.length)}</div>
  <div class="match-score"><b>${Number(p.score||0).toLocaleString("ru-RU")}</b><small>ОЧКИ</small></div></article>`}

function bindMatchCards(){$$('[data-match]').forEach(card=>card.addEventListener("click",()=>openMatch(card.dataset.match)))}
function bindPerks(root=document){root.querySelectorAll('.perk[data-perk-name]').forEach(button=>{if(button.dataset.bound)return;button.dataset.bound="true";button.onclick=event=>{event.stopPropagation();openPerk({id:button.dataset.perkId,name:button.dataset.perkName,image:button.dataset.perkImage},"Навык")}});root.querySelectorAll('.equipment-slot[data-detail-name],.match-character-class[data-detail-name]').forEach(button=>{if(button.dataset.bound)return;button.dataset.bound="true";button.onclick=event=>{event.stopPropagation();openPerk({id:button.dataset.detailId,name:button.dataset.detailName,image:button.dataset.detailImage,owner:button.dataset.detailOwner||""},button.dataset.detailKind||"Снаряжение")}})}
function renderMatches(){const sorted=[...(state.matches||[])].sort((a,b)=>b.startTime-a.startTime),recent=activeRole==="all"?sorted:sorted.filter(m=>m.player?.role===activeRole),history=historyRole==="all"?sorted:sorted.filter(m=>m.player?.role===historyRole);$("#recentMatches").innerHTML=recent.slice(0,5).map(matchCard).join("")||"<p>В этой категории пока нет матчей.</p>";$("#historyMatches").innerHTML=history.map(matchCard).join("")||"<p>В этой категории пока нет матчей.</p>";bindMatchCards();bindPerks()}
function officialCharacters(role,timeframe=characterTimeframe){const key=role==="killer"?"killers":"survivors";return state.officialStats?.timeframes?.[timeframe]?.[key]||[]}
function topCharacterCard(character,index){const rateLabel=character.role==="killer"?"Частота убийств":"Частота побегов";return `<button class="top-character-card" data-character-id="${esc(character.id)}" data-character-role="${character.role}"><span class="top-character-rank">${index+1}</span><div class="top-character-image">${character.image?`<img src="${esc(character.image)}" alt="${esc(character.name)}">`:""}</div><div class="top-character-copy"><h3>${esc(character.name)}</h3><div class="character-stat-line"><span>Часов</span><b>${hoursText(character.hoursPlayed)}</b></div><div class="character-stat-line"><span>Частота выборов</span><b>${percentText(character.pickRate)}</b></div><div class="character-stat-line"><span>${rateLabel}</span><b>${percentText(character.performanceRate)}</b></div></div></button>`}
function characterTableRow(character,index,role,extraClass=""){return `<button class="character-row ${extraClass}" data-character-id="${esc(character.id)}" data-character-role="${role}"><span class="character-row-person"><i class="character-row-rank">${index+1}</i><i class="character-row-image">${character.image?`<img src="${esc(character.image)}" alt="${esc(character.name)}">`:""}</i><b class="character-row-name">${esc(character.name)}</b></span><span>${hoursText(character.hoursPlayed)}</span><span>${percentText(character.pickRate)}</span><span>${percentText(character.performanceRate)}</span></button>`}
function inlineCharacterTable(role,rows){if(characterRole==="all"||rows.length<=3)return"";const rateLabel=role==="killer"?"Частота убийств":"Частота побегов",noun=role==="killer"?"убийцы":"выжившие";return `<section class="inline-character-list"><div class="inline-character-list-title"><div><span class="eyebrow">ОСТАЛЬНЫЕ ПЕРСОНАЖИ</span><h3>Полный рейтинг</h3></div><span>Ещё ${rows.length-3} · места с 4-го</span></div><div class="inline-character-table"><div class="characters-table-head inline-character-table-head"><span>Персонаж</span><span>Часы</span><span>Частота выборов</span><span>${rateLabel}</span></div><div class="inline-character-rows" aria-label="Остальные ${noun}">${rows.slice(3).map((character,index)=>characterTableRow(character,index+3,role,"inline-character-row")).join("")}</div></div></section>`}
function localCharacterFallback(){const grouped={};(state.matches||[]).filter(m=>characterRole==="all"||m.player?.role===characterRole).forEach(m=>{const name=m.player?.character?.name||"Неизвестно",role=m.player?.role||"survivor";grouped[`${role}:${name}`]??={name,role,games:0,kills:0,escapes:0,score:0};const v=grouped[`${role}:${name}`];v.games++;v.kills+=m.kills||0;v.escapes+=escapedResult(m.player?.result)?1:0;v.score+=Number(m.player?.score||0)});const cards=Object.values(grouped).sort((a,b)=>b.games-a.games).map(v=>`<article class="killer-stat-card"><span class="eyebrow">${v.role==="killer"?"УБИЙЦА":"ВЫЖИВШИЙ"}</span><h3>${esc(v.name)}</h3><div><span>Матчей в локальном архиве</span><b>${v.games}</b></div><div><span>${v.role==="killer"?"Убийств":"Побегов"}</span><b>${v.role==="killer"?v.kills:v.escapes}</b></div><div><span>Средние очки</span><b>${Math.round(v.score/v.games).toLocaleString("ru-RU")}</b></div></article>`).join("");return `<div class="official-stats-empty"><b>Расширенная статистика еще не загружена</b><p>Нажмите «Синхронизировать». Companion заберет часы, частоту выборов и полную статистику персонажей из официального DBD Stats Tracker.</p></div><div class="killer-grid">${cards}</div>`}
function renderKillerStats(){const official=state.officialStats,meta=$("#characterStatsMeta"),back=$("#characterOverviewBack");back.hidden=characterRole==="all";if(!official){meta.textContent="Пока показаны данные локальной истории";$("#killerStats").innerHTML=localCharacterFallback();return}const updated=officialDateText(official.updatedAt||official.syncedAt);meta.textContent=`Официальные данные · ${characterTimeframe==="all-time"?"за все время":"за последние 30 дней"}${updated?` · обновлены ${updated}`:""}`;const roles=characterRole==="all"?["killer","survivor"]:[characterRole];$("#killerStats").innerHTML=roles.map(role=>{const rows=officialCharacters(role),title=role==="killer"?"Лучшие убийцы":"Лучшие выжившие",label=role==="killer"?"УБИЙЦЫ":"ВЫЖИВШИЕ",headerAction=characterRole==="all"?`<button data-view-characters="${role}" ${rows.length?"":"disabled"}>Смотреть всех (${rows.length})</button>`:`<span class="character-total-count">Всего персонажей: <b>${rows.length}</b></span>`;return `<section class="character-role-section ${characterRole!=="all"?"is-expanded":""}"><div class="character-role-header"><div><span class="eyebrow">${label}</span><h2>${title}</h2></div>${headerAction}</div>${rows.length?`<div class="top-characters-grid">${rows.slice(0,3).map(topCharacterCard).join("")}</div>${inlineCharacterTable(role,rows)}`:`<div class="official-stats-empty"><b>Нет данных за этот период</b><p>Официальный трекер пока не вернул матчи для этой роли.</p></div>`}</section>`}).join("");$$('[data-view-characters]').forEach(button=>button.onclick=()=>showCharacterRole(button.dataset.viewCharacters));$$('#killerStats [data-character-id]').forEach(button=>button.onclick=()=>openCharacterDetail(button.dataset.characterRole,button.dataset.characterId))}
function showCharacterRole(role){characterRole=role==="killer"?"killer":role==="survivor"?"survivor":"all";renderKillerStats();$("#killersPage").scrollTop=0}

function openCharacters(role){const rows=officialCharacters(role);$("#charactersModalTitle").textContent=role==="killer"?"Все убийцы":"Все выжившие";$("#charactersRateHead").textContent=role==="killer"?"Частота убийств":"Частота побегов";$("#charactersTable").innerHTML=rows.map((character,index)=>characterTableRow(character,index,role)).join("");$("#charactersModal").classList.add("open");$$('#charactersTable [data-character-id]').forEach(button=>button.onclick=()=>openCharacterDetail(button.dataset.characterRole,button.dataset.characterId))}

const killerMetricLabels=[["matches_played","Матчей сыграно","number"],["survivors_killed","Всего убийств","number"],["kill_rate","Частота убийств","percent"],["killer_hooks","Всего подвешиваний","number"],["killer_avg_hooks_per_match","Среднее количество подвешиваний","number"],["bp_earned_through_match","Очков крови","number"],["avg_bp_earned_per_match","Средние очки крови","number"],["killer_hits_any","Ударов","number"],["killer_chases_won","Выиграно погонь","number"],["killer_generators_kicked","Генераторов повреждено","number"],["killer_pallets_destroyed","Паллет сломано","number"],["killer_walls_broken","Стен сломано","number"]];
const survivorMetricLabels=[["matches_played","Матчей сыграно","number"],["matches_escaped","Побегов","number"],["escape_rate","Частота побегов","percent"],["bp_earned_through_match","Очков крови","number"],["avg_bp_earned_per_match","Средние очки крови","number"],["survivor_successfully_healed","Успешных лечений","number"],["survivor_times_hooked","Раз на крюке","number"],["survivor_avg_times_hooked_per_match","Среднее крюков","number"],["survivor_chases_won","Выиграно погонь","number"],["survivor_longest_chase_time_in_seconds","Самая долгая погоня","duration"]];
function metricText(value,type){if(type==="percent")return percentText(value);if(type==="duration")return durationText(value);return numberText(value)}
function openCharacterDetail(role,id){const character=officialCharacters(role).find(item=>String(item.id)===String(id));if(!character)return;$("#characterDetailRole").textContent=role==="killer"?"УБИЙЦА":"ВЫЖИВШИЙ";$("#characterDetailName").textContent=character.name;$("#characterDetailImage").src=character.image||"";const base=[["hours_played_in_match","Часов сыграно","hours"],["pick_rate","Частота выборов","percent"],[role==="killer"?"kill_rate":"escape_rate",role==="killer"?"Частота убийств":"Частота побегов","percent"]],metrics=role==="killer"?killerMetricLabels:survivorMetricLabels,seen=new Set();$("#characterDetailStats").innerHTML=[...base,...metrics].filter(([key])=>!seen.has(key)&&seen.add(key)).map(([key,label,type])=>{const value=key==="hours_played_in_match"?character.hoursPlayed:key==="pick_rate"?character.pickRate:key==="kill_rate"||key==="escape_rate"?character.performanceRate:character.metrics?.[key];if(value===undefined)return"";return `<div class="character-detail-stat"><span>${label}</span><b>${type==="hours"?hoursText(value):metricText(value,type)}</b></div>`}).join("");$("#characterDetailModal").classList.add("open")}

const cleanWikiText=value=>String(value||"").replace(/\[\s*править\s*\]/gi,"").replace(/\[\s*\d+\s*\]/g,"").replace(/\s+/g," ").trim();
const directListItems=node=>[...(node?.children||[])].filter(child=>child.tagName==="LI").map(child=>cleanWikiText(child.textContent)).filter(Boolean);
function findAddonRow(doc,name){const wanted=cleanWikiText(name).toLocaleLowerCase("ru-RU"),rows=[...doc.querySelectorAll('.mw-parser-output table tr')];return rows.find(row=>{const cells=row.querySelectorAll(':scope > td');if(cells.length<3)return false;const title=cleanWikiText(cells[1].textContent).replace(/\(англ\.[\s\S]*$/i,"").trim().toLocaleLowerCase("ru-RU");return title===wanted||title.startsWith(wanted)})}
function addonDetailsFromWiki(doc,name){const row=findAddonRow(doc,name);if(!row)return null;const cell=row.querySelectorAll(':scope > td')[2],clone=cell.cloneNode(true),list=clone.querySelector('ul'),quoteNode=[...clone.querySelectorAll('p')].find(node=>node.querySelector('i'))||clone.querySelector('i'),characteristics=directListItems(list);list?.remove();if(quoteNode){const parent=quoteNode.closest('p')||quoteNode;parent.remove()}const description=cleanWikiText(clone.textContent);return{description,quote:cleanWikiText(quoteNode?.textContent).replace(/^['"«]|['"»]$/g,"").trim(),characteristics,features:[],featuresLead:""}}
function itemDetailsFromWiki(doc){const root=doc.querySelector('.mw-parser-output');if(!root)return null;const children=[...root.children],featuresIndex=children.findIndex(node=>node.tagName==="H2"&&/^Особенности/i.test(cleanWikiText(node.textContent))),firstHeadingIndex=children.findIndex(node=>node.tagName==="H2"),introEnd=firstHeadingIndex<0?children.length:firstHeadingIndex,pre=children.slice(0,introEnd).filter(node=>node.tagName!=="ASIDE"&&!node.matches('.fandom-ad-wrapper,.incontent_leaderboard')),descriptionNode=pre.find(node=>node.tagName==="P"&&cleanWikiText(node.textContent).length>35),quoteDecoration=root.querySelector('img[data-image-name^="Pq_lTopTemplate"],img[alt^="Pq lTopTemplate"]'),quoteContainer=quoteDecoration?.closest('div'),quoteNode=quoteContainer?.querySelector('dl i'),characteristicsNode=pre.find(node=>node.tagName==="UL"||node.tagName==="OL")||children.slice(introEnd).find(node=>node.tagName==="UL"||node.tagName==="OL"),description=cleanWikiText(descriptionNode?.textContent),quote=cleanWikiText(quoteNode?.textContent).replace(/^[«“"']+|[»”"']+$/g,"").trim(),characteristics=directListItems(characteristicsNode),characteristicsIndex=children.indexOf(characteristicsNode);if(characteristicsIndex>=0&&characteristicsIndex<introEnd){for(const node of children.slice(characteristicsIndex+1,introEnd)){if(node.tagName!=="P")continue;const text=cleanWikiText(node.textContent);if(text&&!/команда Dead by Daylight/i.test(text))characteristics.push(text)}}let featuresLead="",features=[];if(featuresIndex>=0){for(let i=featuresIndex+1;i<children.length&&children[i].tagName!=="H2";i++){const node=children[i];if(!featuresLead&&node.tagName==="P")featuresLead=cleanWikiText(node.textContent);if(!features.length&&(node.tagName==="UL"||node.tagName==="OL"))features=directListItems(node)}}return{description,quote,characteristics:[...new Set(characteristics)],features,featuresLead}}
function descriptionFromWiki(html,name,kind){const doc=new DOMParser().parseFromString(html,"text/html");if(/^Аддон/i.test(kind||"")){const addon=addonDetailsFromWiki(doc,name);if(addon)return addon}const item=itemDetailsFromWiki(doc);if(item&&(item.description||item.characteristics.length||item.features.length))return item;const heading=doc.querySelector('#Описание')?.closest('h2'),parts=[];if(heading){for(let node=heading.nextElementSibling;node&&node.tagName!=="H2";node=node.nextElementSibling){const text=cleanWikiText(node.textContent);if(text)parts.push(text)}}const direct=cleanWikiText(doc.querySelector('.perkDesc')?.textContent)||parts.join("\n\n")||[...doc.querySelectorAll('.mw-parser-output > p')].map(node=>cleanWikiText(node.textContent)).filter(text=>text.length>35&&!/^(Эта статья|Навигация|Реклама)/i.test(text)).slice(0,4).join("\n\n");return{description:direct,quote:"",characteristics:[],features:[],featuresLead:""}}
function renderDetailList(selector,sectionSelector,items){const list=$(selector),values=(items||[]).filter(Boolean);list.innerHTML=values.map(item=>`<li>${esc(item)}</li>`).join("");$(sectionSelector).hidden=!values.length}
async function openPerk(perk,kind="Навык"){lastDetailRequest={perk:{...perk},kind};const token=++perkRequestToken,status=$("#perkDetailStatus"),retry=$("#perkRetryButton");$("#perkDetailKind").textContent=`ОПИСАНИЕ · ${String(kind).toUpperCase()}`;$("#perkDetailTitle").textContent=perk.name||kind;$("#perkDetailImage").src=perk.image||"";status.textContent="Загрузка описания…";status.hidden=false;retry.hidden=true;retry.disabled=true;$("#perkDetailDescription").textContent="";$("#perkDetailQuote").hidden=true;$("#perkCharacteristicsSection").hidden=true;$("#perkFeaturesSection").hidden=true;$("#perkSourceButton").hidden=true;$("#perkModal").classList.add("open");try{const details=await window.fogAPI.getPerkDetails(perk,kind);if(token!==perkRequestToken)return;const parsed=descriptionFromWiki(details.html,perk.name,kind);const found=Boolean(parsed.description||parsed.quote||parsed.characteristics.length||parsed.features.length);status.textContent=found?"":"Описание не найдено";status.hidden=found;$("#perkDetailDescription").textContent=parsed.description||`Для элемента «${perk.name||kind}» пока нет доступного полного описания.`;$("#perkDetailQuote").textContent=parsed.quote;$("#perkDetailQuote").hidden=!parsed.quote;renderDetailList("#perkDetailCharacteristics","#perkCharacteristicsSection",parsed.characteristics);$("#perkFeaturesLead").textContent=parsed.featuresLead||"";renderDetailList("#perkDetailFeatures","#perkFeaturesSection",parsed.features);$("#perkSourceButton").hidden=!details.sourceUrl;$("#perkSourceButton").dataset.url=details.sourceUrl||""}catch(error){if(token!==perkRequestToken)return;status.hidden=false;status.textContent="Не удалось загрузить описание";$("#perkDetailDescription").textContent="Источник описаний временно недоступен. Проверьте подключение и повторите загрузку.";retry.hidden=false;retry.disabled=false}}
function openMatch(id){const match=state.matches.find(m=>String(m.id)===String(id));if(!match)return;selectedMatch=match;$("#detailTitle").textContent=`${match.player.character.name} — ${match.map}`;const detailMap=$("#detailMap"),mapLayer=match.mapImage?`url("${String(match.mapImage).replace(/["\\]/g,"\\$&")}")`:"none";detailMap.style.backgroundImage=`linear-gradient(90deg,rgba(7,7,9,.9),rgba(7,7,9,.18) 72%),linear-gradient(0deg,rgba(7,7,9,.72),transparent 70%),${mapLayer}`;detailMap.innerHTML=`<div class="detail-map-copy"><small>КАРТА</small><b>${esc(match.map||"Неизвестная карта")}</b></div>`;$("#detailSummary").innerHTML=[["Дата",dateText(match.startTime)],["Длительность",durationText(match.duration)],["Режим",gameTypeText(match.gameType)],["Убийства",Number.isFinite(match.kills)?`${match.kills} из ${survivorCapacity(match)}`:"—"]].map(([a,b])=>`<div class="detail-stat"><small>${a}</small><b>${esc(b)}</b></div>`).join("");const players=[match.player,...(match.participants||[])].sort((a,b)=>a.role===b.role?(a.role==="survivor"?Number(b.score||0)-Number(a.score||0):0):a.role==="survivor"?-1:1);$("#scoreRows").innerHTML=players.map((p,i)=>{const isSelf=p===match.player,label=isSelf&&state.account?.name?state.account.name:participantLabel(p,i),profileUrl=isSelf&&state.account?.profileUrl?state.account.profileUrl:p.profileUrl,title=profileUrl?"Открыть профиль Steam":"Официальный трекер не передает ник или профиль этого игрока";return `<div class="score-row ${isSelf?"is-self":""}"><div class="score-player"><button type="button" class="score-player-link ${profileUrl?"has-profile":""}" title="${title}" ${profileUrl?`data-profile-url="${esc(profileUrl)}"`:"disabled"}><div class="portrait">${imageOrInitial(p.character?.image,p.character?.name)}</div><div><b>${esc(label)}${isSelf?'<em class="you-badge">ВЫ</em>':""}</b><small>${esc(p.character?.name)}</small></div></button></div><div class="score-result ${resultClass(p.result)}">${esc(resultText(p.result)||"—")}</div>${loadoutHtml(p,match)}<div class="score-points">${Number(p.score||0).toLocaleString("ru-RU")}</div></div>`}).join("");$("#matchModal").classList.add("open");bindPerks($("#scoreRows"));$$('[data-profile-url]').forEach(button=>button.onclick=()=>window.fogAPI.openExternal(button.dataset.profileUrl))}

function switchPage(name){if(name==="killers"){characterRole="all";renderKillerStats()}$$('.nav-link').forEach(b=>b.classList.toggle("active",b.dataset.page===name));$$('.page').forEach(p=>p.classList.remove("active"));$(`#${name}Page`).classList.add("active")}
function renderSettings(){const s=state.settings||{};$("#searchPointLabel").textContent=pointText(s.searchPoint);$("#resultPointLabel").textContent=pointText(s.resultPoint);["perkSlot1","perkSlot2","perkSlot3","perkSlot4","perkSearch","perkResult","perkClear"].forEach(key=>{$(`#${key}PointLabel`).textContent=pointText(s[`${key}Point`])});$("#automationToggle").checked=Boolean(s.automationEnabled);renderWheelSettings()}
function renderUpdateStatus(value={}){const text=$("#updateStatusText"),version=$("#updateVersionText"),button=$("#updateButton"),badge=$("#appVersionBadge");if(badge&&value.currentVersion)badge.textContent=value.currentVersion;if(!text||!version||!button)return;text.textContent=value.message||"Обновления еще не проверялись.";version.textContent=`Текущая версия ${value.currentVersion||"—"}${value.latestVersion&&value.latestVersion!==value.currentVersion?` · последняя ${value.latestVersion}`:""}`;button.disabled=["checking","downloading","installing"].includes(value.status);button.textContent=value.status==="available"?"Скачать и установить":value.status==="downloading"?"Скачивание…":value.status==="installing"?"Перезапуск…":"Проверить обновления";button.dataset.action=value.status==="available"?"install":"check";if(value.notify&&value.status==="available")showToast(value.message,"success")}
function renderAll(){renderProfile();renderSummary();renderMatches();renderKillerStats();renderSettings()}
function applyHistorySearch(){const q=$("#historySearch").value.trim().toLowerCase();$$('#historyMatches .match-card').forEach(card=>{const m=state.matches.find(x=>String(x.id)===card.dataset.match);const haystack=m?`${m.map||""} ${m.player?.character?.name||""} ${m.player?.nickname||""}`.toLowerCase():"";card.style.display=!q||haystack.includes(q)?"grid":"none"})}
async function checkGame(){const running=await window.fogAPI.getGameStatus();const el=$("#gameIndicator");el.classList.toggle("online",running);el.innerHTML=`<i></i>${running?"Dead by Daylight запущен":"Dead by Daylight не запущен"}`}

const palette=["#6c1d22","#222329","#8b252b","#303137","#51181c","#28292f"];
function enabledKillers(){const ids=state.settings?.enabledKillerIds||[];return window.FOG_KILLERS.filter(killer=>ids.includes(killer.id))}
function wheelKillers(){const killers=enabledKillers(),cooldown=Math.max(0,Number(state.settings?.wheelCooldown)||0),blocked=new Set((state.randomizer?.killerHistory||[]).slice(-cooldown));if(!cooldown)return killers;const available=killers.filter(killer=>!blocked.has(killer.id));return available.length?available:killers}
function applyWheelRotation(){const canvas=$("#wheelCanvas");canvas.style.transform=`translateZ(0) rotate(${wheelRotation}rad)`}
function drawWheel(){const canvas=$("#wheelCanvas"),ctx=canvas.getContext("2d",{alpha:true}),killers=wheelKillers(),size=900,c=size/2,r=c-18,empty=!killers.length;ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,size,size);canvas.parentElement.classList.toggle("empty-wheel",empty);$("#spinWheel").hidden=empty;if(empty){canvas.style.transform="translateZ(0)";ctx.beginPath();ctx.arc(c,c,r,0,Math.PI*2);ctx.fillStyle="#202126";ctx.fill();ctx.strokeStyle="#c7c0ba";ctx.lineWidth=5;ctx.stroke();ctx.fillStyle="#b8b2b6";ctx.font="700 28px Segoe UI";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("ВКЛЮЧИТЕ ХОТЯ БЫ ОДНОГО УБИЙЦУ",c,c);return}const arc=Math.PI*2/killers.length;killers.forEach((k,i)=>{const start=i*arc-Math.PI/2;ctx.beginPath();ctx.moveTo(c,c);ctx.arc(c,c,r,start,start+arc);ctx.closePath();ctx.fillStyle=palette[i%palette.length];ctx.fill();ctx.strokeStyle="rgba(255,255,255,.11)";ctx.lineWidth=2;ctx.stroke();ctx.save();ctx.translate(c,c);ctx.rotate(start+arc/2);ctx.textAlign="right";ctx.textBaseline="middle";ctx.fillStyle="#eee9e4";ctx.font=`${killers.length>35?17:19}px Segoe UI`;const label=k.name.length>13?k.name.slice(0,12)+"…":k.name;ctx.fillText(label.toUpperCase(),r-25,0);ctx.restore()});ctx.beginPath();ctx.arc(c,c,r,0,Math.PI*2);ctx.strokeStyle="#b7afa9";ctx.lineWidth=5;ctx.stroke();applyWheelRotation()}
function randomIndex(max){const a=new Uint32Array(1),limit=0xffffffff-(0xffffffff%max);do{crypto.getRandomValues(a)}while(a[0]>=limit);return a[0]%max}
function setWheelPortrait(killer){const portrait=$("#wheelResultPortrait"),image=$("#wheelResultImage"),fallback=portrait.querySelector("span");image.onload=()=>{image.hidden=false;portrait.classList.remove("portrait-error")};image.onerror=()=>{image.hidden=true;fallback.textContent=killer?.name?.slice(0,1)||"?";portrait.classList.add("portrait-error")};if(killer){portrait.classList.remove("mystery","portrait-error");fallback.textContent=killer.name?.slice(0,1)||"?";image.hidden=false;image.src=killer.image||"";image.alt=killer.name}else{portrait.classList.add("mystery");portrait.classList.remove("portrait-error");fallback.textContent="?";image.hidden=false;image.removeAttribute("src");image.alt=""}setPortraitFogActive(portrait,Boolean(killer))}
function spinWheel(){if(wheelSpinning)return;const killers=wheelKillers();if(!killers.length){showToast("Включите хотя бы одного убийцу в настройках колеса","error");return}const winner=randomIndex(killers.length),arc=Math.PI*2/killers.length,start=wheelRotation,norm=((start%(Math.PI*2))+Math.PI*2)%(Math.PI*2),base=-winner*arc-arc/2;let delta=((base-norm)%(Math.PI*2)+Math.PI*2)%(Math.PI*2)+(7+randomIndex(3))*Math.PI*2,duration=4300,at=performance.now();wheelSpinning=true;selectedKiller=null;setWheelPortrait(null);$("#spinWheel").disabled=true;$("#saveKillerForOverlay").disabled=true;$("#saveKillerForOverlay").textContent="Выбрать убийцу";$("#spinAgain").disabled=true;$("#wheelResultName").textContent="Колесо решает…";function frame(now){const t=Math.min(1,(now-at)/duration),ease=1-Math.pow(1-t,4);wheelRotation=start+delta*ease;applyWheelRotation();if(t<1)requestAnimationFrame(frame);else{wheelRotation=base;applyWheelRotation();wheelSpinning=false;selectedKiller=killers[winner];setWheelPortrait(selectedKiller);$("#spinWheel").disabled=false;$("#spinAgain").disabled=false;$("#saveKillerForOverlay").disabled=false;$("#wheelResultName").textContent=selectedKiller.name;$("#wheelStatus").textContent="Нажмите «Выбрать убийцу», чтобы перенести результат во внутриигровой оверлей.";const killerHistory=[...(state.randomizer?.killerHistory||[]),selectedKiller.id].slice(-50);state.randomizer={...(state.randomizer||{}),killerHistory};window.fogAPI.saveRandomizer({killerHistory}).then(value=>{state=value})}}requestAnimationFrame(frame)}
async function saveKillerForOverlay(){if(!selectedKiller)return;state=await window.fogAPI.saveRandomizer({killer:selectedKiller,killerHistory:state.randomizer?.killerHistory||[]});$("#saveKillerForOverlay").disabled=true;$("#saveKillerForOverlay").textContent="Сохранено для внутриигрового оверлея";$("#wheelStatus").textContent="Откройте DBD и нажмите Shift+F2 — выбранный убийца уже будет ждать там.";showToast(`${selectedKiller.name} сохранен для внутриигрового оверлея`,"success")}
function knownKillerPerks(){const result=new Map();for(const match of state.matches||[])for(const person of [match.player,...(match.participants||[])])if(person?.role==="killer")for(const raw of person.perks||[]){const perk=localizedPerk(raw),key=String(perk.id||perk.name).toLocaleLowerCase("ru-RU");if(perk.name&&!result.has(key))result.set(key,{id:perk.id||perk.name,name:perk.name,image:perk.image||""})}return [...result.values()]}
function allKillerPerks(){
  const catalog=perkCatalog.map(localizedPerk).filter(isRealKillerPerk),byName=new Map();
  catalog.forEach((perk,index)=>{const key=String(perk.name||"").trim().toLocaleLowerCase("ru-RU").replace(/ё/g,"е"),list=byName.get(key)||[];list.push(index);byName.set(key,list)});
  for(const raw of knownKillerPerks()){
    const perk=localizedPerk(raw);if(!isRealKillerPerk(perk))continue;
    const key=String(perk.name||"").trim().toLocaleLowerCase("ru-RU").replace(/ё/g,"е"),matches=byName.get(key)||[];
    if(matches.length===1){const index=matches[0],current=catalog[index];catalog[index]={...perk,...current,name:current.name||perk.name,image:current.image||perk.image||""};continue}
    if(!matches.length){byName.set(key,[catalog.length]);catalog.push(perk)}
  }
  return catalog;
}
function enabledPerks(){const ids=new Set(state.settings?.enabledPerkIds||[]),all=allKillerPerks();return state.settings?.perkFilterInitialized?all.filter(perk=>ids.has(String(perk.id))):all}
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function preloadPerkImages(perks){const urls=[...new Set(perks.map(perk=>perk?.image).filter(Boolean))];return Promise.all(urls.map(url=>new Promise(resolve=>{const image=new Image(),done=()=>resolve();image.onload=done;image.onerror=done;image.src=url;setTimeout(done,4500)})))}
function setPerkSlotVisual(index,perk,rolling=false){const card=document.querySelector(`[data-perk-slot="${index}"]`);if(!card)return;card.classList.toggle("rolling",rolling);const image=card.querySelector(".random-perk-image"),name=card.querySelector("[data-perk-name]"),displayName=perkDisplayName(perk);image.querySelectorAll(".perk-reel-outgoing").forEach(node=>node.remove());const current=image.querySelector(".perk-reel-symbol")||image.firstElementChild;if(rolling&&current){current.classList.add("perk-reel-symbol","perk-reel-outgoing");setTimeout(()=>current.remove(),310)}else image.replaceChildren();const markup=perk?.image?`<img class="perk-reel-symbol ${rolling?"perk-reel-incoming":""}" src="${esc(perk.image)}" alt="${esc(displayName)}">`:`<span class="perk-reel-symbol ${rolling?"perk-reel-incoming":""}">?</span>`;image.insertAdjacentHTML("beforeend",markup);name.textContent=displayName||"Случайный перк"}
function renderPerkRandomizer(){const slots=$("#perkRandomizerSlots");slots.innerHTML=[0,1,2,3].map(index=>{const perk=selectedPerks[index],locked=Boolean(perkLocks[index]),displayName=perkDisplayName(perk);return `<article class="random-perk-card ${locked?"locked":""}" data-perk-slot="${index}"><button type="button" class="perk-lock" data-perk-lock="${index}" aria-pressed="${locked}" ${perkSpinning?"disabled":""}>${locked?"🔒 Закреплен":"🔓 Закрепить"}</button><div class="random-perk-image">${perk?.image?`<img class="perk-reel-symbol" src="${esc(perk.image)}" alt="${esc(displayName)}">`:'<span class="perk-reel-symbol">?</span>'}</div><b data-perk-name>${esc(displayName||"Случайный перк")}</b></article>`}).join("");$$('[data-perk-lock]').forEach(button=>button.onclick=()=>{const index=Number(button.dataset.perkLock);if(!selectedPerks[index]||perkSpinning)return;perkLocks[index]=!perkLocks[index];renderPerkRandomizer()});$("#savePerksForOverlay").disabled=perkSpinning||selectedPerks.filter(Boolean).length!==4;$("#rerollPerks").disabled=perkSpinning}
async function rerollPerks(){if(perkSpinning)return;const catalog=enabledPerks();if(catalog.length<4){showToast("Включите хотя бы четыре перка в настройках рандомайзера","error");return}const unlocked=[0,1,2,3].filter(index=>!perkLocks[index]||!selectedPerks[index]);if(!unlocked.length){showToast("Все четыре перка закреплены");return}const cooldown=Math.max(0,Number(state.settings?.perkCooldown)||0),history=(state.randomizer?.perkHistory||[]).filter(Array.isArray),blocked=new Set(history.slice(-cooldown).flat().map(String)),used=new Set(selectedPerks.filter((_,index)=>perkLocks[index]).map(perk=>String(perk.id))),next=[...selectedPerks],rolled=[];for(const index of unlocked){let available=catalog.filter(perk=>!used.has(String(perk.id))&&!blocked.has(String(perk.id)));if(!available.length)available=catalog.filter(perk=>!used.has(String(perk.id)));const perk=available[randomIndex(available.length)];next[index]=perk;used.add(String(perk.id));rolled.push(String(perk.id))}const sequences=new Map(unlocked.map((index,offset)=>{const sequence=[];for(let step=0;step<16+offset*2;step++)sequence.push(catalog[randomIndex(catalog.length)]);sequence.push(next[index]);return[index,sequence]}));perkSpinning=true;renderPerkRandomizer();$("#perkRandomizerStatus").textContent="Загружаю изображения для барабанов…";await preloadPerkImages([...sequences.values()].flat());$("#perkRandomizerStatus").textContent="Перки вращаются…";await Promise.all(unlocked.map(async index=>{const sequence=sequences.get(index);for(let step=0;step<sequence.length;step++){setPerkSlotVisual(index,sequence[step],true);const progress=step/(sequence.length-1),delay=Math.round(165+Math.pow(progress,3)*315);await wait(delay)}setPerkSlotVisual(index,next[index],false)}));selectedPerks=next;const perkHistory=[...history,rolled].slice(-50);state=await window.fogAPI.saveRandomizer({perkHistory});perkSpinning=false;renderPerkRandomizer();$("#perkRandomizerStatus").textContent="Барабаны остановились. Закрепите понравившиеся перки или сохраните сборку.";$("#savePerksForOverlay").textContent="Сохранить для оверлея"}
async function savePerksForOverlay(){if(selectedPerks.filter(Boolean).length!==4)return;state=await window.fogAPI.saveRandomizer({perks:selectedPerks,perkLocks});$("#savePerksForOverlay").disabled=true;$("#savePerksForOverlay").textContent="Сохранено для внутриигрового оверлея";$("#perkRandomizerStatus").textContent="Откройте экран перков в DBD, затем Shift+F2 и запустите автовыбор."}
function renderWheelSettings(){const s=state.settings||{},grid=$("#killerToggleGrid");if(!grid)return;$("#wheelCooldownInput").value=Math.max(0,Number(s.wheelCooldown)||0);$("#perkCooldownInput").value=Math.max(0,Number(s.perkCooldown)||0);const enabled=new Set(s.enabledKillerIds||[]);grid.innerHTML=window.FOG_KILLERS.map(killer=>`<label class="killer-toggle-card ${enabled.has(killer.id)?"enabled":""}"><input type="checkbox" data-killer-toggle="${esc(killer.id)}" ${enabled.has(killer.id)?"checked":""}><i class="killer-toggle-control" aria-hidden="true"></i><span class="killer-toggle-name">${esc(killer.name)}</span><span class="killer-toggle-portrait">${killer.image?`<img src="${esc(killer.image)}" alt="" loading="lazy" decoding="async">`:""}</span></label>`).join("");$$('[data-killer-toggle]').forEach(input=>input.onchange=()=>{const card=input.closest(".killer-toggle-card");card.classList.toggle("enabled",input.checked);card.classList.remove("just-toggled");requestAnimationFrame(()=>{card.classList.add("just-toggled");setTimeout(()=>card.classList.remove("just-toggled"),660)});saveKillerToggles()});renderPerkToggles()}
function renderPerkToggles(){const grid=$("#perkToggleGrid"),all=allKillerPerks(),enabled=new Set(state.settings?.enabledPerkIds||[]),query=perkFilterQuery.toLocaleLowerCase("ru-RU"),filtered=all.filter(perk=>!query||perk.name.toLocaleLowerCase("ru-RU").includes(query));grid.innerHTML=filtered.length?filtered.map(perk=>`<label title="${esc(perk.name)}"><input type="checkbox" data-perk-toggle="${esc(perk.id)}" ${enabled.has(String(perk.id))?"checked":""}><span>${esc(perk.name)}</span></label>`).join(""):'<span class="settings-loading">Перки не найдены</span>';$$('[data-perk-toggle]').forEach(input=>input.onchange=savePerkToggles)}
async function saveKillerToggles(){$$('[data-killer-toggle]').forEach(input=>input.closest(".killer-toggle-card")?.classList.toggle("enabled",input.checked));state.settings.enabledKillerIds=$$('[data-killer-toggle]:checked').map(input=>input.dataset.killerToggle);state.settings.killerFilterInitialized=true;state=await window.fogAPI.saveSettings(state.settings);drawWheel();const empty=!enabledKillers().length;$("#spinAgain").disabled=empty||!selectedKiller;if(empty)$("#saveKillerForOverlay").disabled=true}
async function savePerkToggles(){const visible=new Set($$('[data-perk-toggle]').map(input=>input.dataset.perkToggle)),enabled=new Set(state.settings.enabledPerkIds||[]);for(const id of visible)enabled.delete(id);$$('[data-perk-toggle]:checked').forEach(input=>enabled.add(input.dataset.perkToggle));state.settings.enabledPerkIds=[...enabled];state.settings.perkFilterInitialized=true;state=await window.fogAPI.saveSettings(state.settings)}
function restoreRandomizer(){selectedKiller=state.randomizer?.killer||null;selectedPerks=[...(state.randomizer?.perks||[])];perkLocks=[...(state.randomizer?.perkLocks||[false,false,false,false])];while(perkLocks.length<4)perkLocks.push(false);setWheelPortrait(selectedKiller);$("#wheelResultName").textContent=selectedKiller?.name||"Крути колесо";$("#spinAgain").disabled=!selectedKiller;$("#saveKillerForOverlay").disabled=true;$("#saveKillerForOverlay").textContent=selectedKiller?"Сохранено для внутриигрового оверлея":"Выбрать убийцу";$("#wheelStatus").textContent=selectedKiller?"Этот результат уже сохранен и появится в оверлее Shift+F2.":"Прокрутите колесо и сохраните результат для внутриигрового оверлея.";renderPerkRandomizer()}
function setRandomizerTab(tab){activeRandomizerTab=tab==="perks"?"perks":"killer";$$('[data-randomizer-tab]').forEach(item=>item.classList.toggle("active",item.dataset.randomizerTab===activeRandomizerTab));const perks=activeRandomizerTab==="perks";$("#killerRandomizerPanel").hidden=perks;$("#perkRandomizerPanel").hidden=!perks;$("#wheelSettingsPanel").hidden=perks;$("#perkSettingsPanel").hidden=!perks;if(perks)renderPerkToggles();else drawWheel()}
async function loadPerkCatalog(){try{const result=await window.fogAPI.getKillerPerks();perkCatalog=(result.items||[]).filter(isRealKillerPerk);if(result.data)state=result.data;renderPerkToggles();return true}catch(error){perkCatalog=(state.perkCatalog?.items||[]).filter(isRealKillerPerk);renderPerkToggles();showToast(`Не удалось обновить каталог перков: ${error?.message||error}`,"error");return false}}

function bind(){
  const loginSteam=async()=>{const buttons=[$("#steamLoginButton"),$("#steamAccountButton")];buttons.forEach(button=>button.disabled=true);$("#authGateStatus").textContent="Открываю официальную страницу Steam…";try{state=await window.fogAPI.loginSteam();renderAll();showToast(`Вход выполнен: ${state.account?.name||"Steam"}`,"success")}catch(error){const message=String(error?.message||"Не удалось войти через Steam").replace(/^Error invoking remote method '[^']+': Error:\s*/,"");$("#authGateStatus").textContent=message;showToast(message,"error")}finally{buttons.forEach(button=>button.disabled=false)}};
  $("#steamLoginButton").onclick=loginSteam;$("#steamAccountButton").onclick=loginSteam;$("#accountLogoutButton").onclick=async()=>{state=await window.fogAPI.logoutAccount();renderAll()};
  $("#minimize").onclick=()=>window.fogAPI.minimize();$("#maximize").onclick=()=>window.fogAPI.maximize();$("#close").onclick=()=>window.fogAPI.close();
  $$('.nav-link').forEach(b=>b.onclick=()=>switchPage(b.dataset.page));$("#showAllHistory").onclick=()=>switchPage("history");$("#chartOpenHistory").onclick=()=>switchPage("history");$("#historyBack").onclick=()=>switchPage("overview");$("#chartInfo").onclick=()=>{const scope=activeRole==="killer"?"Матчи за убийцу":activeRole==="survivor"?"Матчи за выжившего":"Матчи за убийцу и выжившего";$("#chartTooltip").innerHTML=`<b>${scope} за 30 дней</b><br>Красный столбец — доля убитых выживших в матче (из 4 или 8), голубой — побег. Нажатие открывает матч.`};
  $$('.role-switch [data-role]').forEach(button=>button.onclick=()=>{activeRole=button.dataset.role;$$('.role-switch [data-role]').forEach(item=>item.classList.toggle("active",item===button));renderSummary();renderMatches()});
  $$('[data-history-role]').forEach(button=>button.onclick=()=>{historyRole=button.dataset.historyRole;$$('[data-history-role]').forEach(item=>item.classList.toggle("active",item===button));renderMatches();applyHistorySearch()});
  $("#characterOverviewBack").onclick=()=>showCharacterRole("all");
  $$('[data-character-timeframe]').forEach(button=>button.onclick=()=>{characterTimeframe=button.dataset.characterTimeframe;$$('[data-character-timeframe]').forEach(item=>item.classList.toggle("active",item===button));renderKillerStats()});
  $("#syncSideButton").onclick=()=>window.fogAPI.openStatsSync();$("#behaviourLogoutButton").onclick=async()=>{state=await window.fogAPI.logoutStats();renderAll()};
  $("#updateButton").onclick=async()=>{const action=$("#updateButton").dataset.action;try{renderUpdateStatus(action==="install"?{status:"downloading",currentVersion:"",message:"Начинаю загрузку обновления…"}:{status:"checking",currentVersion:"",message:"Проверяю GitHub Releases…"});const result=action==="install"?await window.fogAPI.installUpdate():await window.fogAPI.checkForUpdates();if(result&&result!==true)renderUpdateStatus(result)}catch(error){showToast(error?.message||"Не удалось обновить приложение","error");renderUpdateStatus(await window.fogAPI.getUpdateStatus())}};
  $("#diagnosticsButton").onclick=async()=>{try{await window.fogAPI.openDiagnostics()}catch(error){showToast(error?.message||"Не удалось открыть папку с логами","error")}};
  const openWheel=()=>{$("#wheelModal").classList.add("open");restoreRandomizer();renderWheelSettings();setRandomizerTab(activeRandomizerTab);if(!perkCatalog.length)loadPerkCatalog()},wheelEntry=$("#openWheel");wheelEntry.onclick=openWheel;wheelEntry.onkeydown=event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();openWheel()}};$("#spinWheel").onclick=spinWheel;$("#spinAgain").onclick=spinWheel;$("#saveKillerForOverlay").onclick=saveKillerForOverlay;$("#rerollPerks").onclick=rerollPerks;$("#savePerksForOverlay").onclick=savePerksForOverlay;
  $$('[data-randomizer-tab]').forEach(button=>button.onclick=()=>setRandomizerTab(button.dataset.randomizerTab));
  $("#wheelSettingsToggle").onclick=()=>{$("#randomizerSettingsHost").hidden=!$("#randomizerSettingsHost").hidden;setRandomizerTab(activeRandomizerTab)};
  $("#wheelCooldownInput").onchange=async()=>{state.settings.wheelCooldown=Math.max(0,Math.min(50,Number($("#wheelCooldownInput").value)||0));state=await window.fogAPI.saveSettings(state.settings);drawWheel()};
  $("#perkCooldownInput").onchange=async()=>{state.settings.perkCooldown=Math.max(0,Math.min(50,Number($("#perkCooldownInput").value)||0));state=await window.fogAPI.saveSettings(state.settings)};
  $$('[data-number-step]').forEach(button=>button.onclick=()=>{const input=document.getElementById(button.dataset.numberTarget),min=Number(input.min||0),max=Number(input.max||50),next=Math.max(min,Math.min(max,(Number(input.value)||0)+Number(button.dataset.numberStep)));input.value=next;input.dispatchEvent(new Event("change"))});
  $("#enableAllKillers").onclick=()=>{$$('[data-killer-toggle]').forEach(input=>input.checked=true);saveKillerToggles()};$("#disableAllKillers").onclick=()=>{$$('[data-killer-toggle]').forEach(input=>input.checked=false);saveKillerToggles()};
  $("#enableAllPerks").onclick=async()=>{state.settings.enabledPerkIds=allKillerPerks().map(perk=>String(perk.id));state.settings.perkFilterInitialized=true;state=await window.fogAPI.saveSettings(state.settings);renderPerkToggles()};$("#disableAllPerks").onclick=async()=>{state.settings.enabledPerkIds=[];state.settings.perkFilterInitialized=true;state=await window.fogAPI.saveSettings(state.settings);renderPerkToggles()};$("#perkFilterSearch").oninput=event=>{perkFilterQuery=event.target.value.trim();renderPerkToggles()};
  $$('[data-close="match"]').forEach(e=>e.onclick=()=>$("#matchModal").classList.remove("open"));$$('[data-close="wheel"]').forEach(e=>e.onclick=()=>$("#wheelModal").classList.remove("open"));$$('[data-close="perk"]').forEach(e=>e.onclick=()=>{perkRequestToken++;$("#perkModal").classList.remove("open")});$$('[data-close="characters"]').forEach(e=>e.onclick=()=>{$("#charactersModal").classList.remove("open");$("#characterDetailModal").classList.remove("open")});$$('[data-close="character-detail"]').forEach(e=>e.onclick=()=>$("#characterDetailModal").classList.remove("open"));$("#perkRetryButton").onclick=()=>{if(lastDetailRequest)openPerk(lastDetailRequest.perk,lastDetailRequest.kind)};$("#perkSourceButton").onclick=()=>window.fogAPI.openExternal($("#perkSourceButton").dataset.url);
  $$('.point-button').forEach(button=>button.onclick=async()=>{showToast("Окно скроется. Наведите курсор на нужную точку…");const result=await window.fogAPI.capturePoint(button.dataset.point);state.settings[`${result.kind}Point`]=result.point;state=await window.fogAPI.saveSettings(state.settings);renderSettings();showToast("Точка сохранена","success")});
  $("#automationToggle").onchange=async()=>{state.settings.automationEnabled=$("#automationToggle").checked;state=await window.fogAPI.saveSettings(state.settings);renderSettings()};
  $("#historySearch").oninput=applyHistorySearch;
  window.addEventListener("keydown",e=>{if(e.code==="Space"&&$("#wheelModal").classList.contains("open")&&!$("#killerRandomizerPanel").hidden){e.preventDefault();spinWheel()}if(e.code==="Escape"){const hadOpenModal=Boolean($(".modal.open"));$("#wheelModal").classList.remove("open");$("#matchModal").classList.remove("open");$("#perkModal").classList.remove("open");$("#charactersModal").classList.remove("open");$("#characterDetailModal").classList.remove("open");if(!hadOpenModal&&$("#historyPage").classList.contains("active"))switchPage("overview")}});
  window.fogAPI.onSyncStatus(value=>{if(value.message)showToast(value.message,value.type);if(value.data){state=value.data;renderAll()}if(value.message&&value.type!=="success"&&value.type!=="silent")$("#lastSyncLabel").textContent=value.message});window.fogAPI.onAuthStatus(value=>{if(value.message){$("#authGateStatus").textContent=value.message;showToast(value.message,value.type)}});window.fogAPI.onGameStatus(value=>showToast(value.message,value.type));window.fogAPI.onUpdateStatus(renderUpdateStatus);window.fogAPI.onWindowShown(checkGame);window.fogAPI.onRandomizerUpdated(value=>{state=value;if(!$("#wheelModal").classList.contains("open"))restoreRandomizer()});
}

(async()=>{state=await window.fogAPI.getData();perkCatalog=state.perkCatalog?.items||[];if(!Array.isArray(state.settings.enabledKillerIds)){state.settings.enabledKillerIds=window.FOG_KILLERS.map(k=>k.id);state.settings.killerFilterInitialized=true;state=await window.fogAPI.saveSettings(state.settings)}bind();renderAll();restoreRandomizer();drawWheel();renderUpdateStatus(await window.fogAPI.getUpdateStatus());checkGame();loadPerkCatalog();setInterval(checkGame,15000)})();
