const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
let state={settings:{},randomizer:{}},selectedKiller=null,selectedPerks=[],perkLocks=[false,false,false,false],rotation=0,spinning=false;
const colors=["#8c2229","#292a30","#641c22","#34353c","#a12830","#25262c"];
function showKillerPortrait(killer){let portrait=document.querySelector(".overlay-result-portrait");if(!portrait){portrait=document.createElement("div");portrait.className="overlay-result-portrait mystery";portrait.innerHTML='<span>?</span><img alt="">';document.querySelector(".result-panel").prepend(portrait)}const image=portrait.querySelector("img"),fallback=portrait.querySelector("span");image.onload=()=>{image.hidden=false;portrait.classList.remove("portrait-error")};image.onerror=()=>{image.hidden=true;fallback.textContent=killer?.name?.slice(0,1)||"?";portrait.classList.add("portrait-error")};if(killer){portrait.classList.remove("mystery","portrait-error");fallback.textContent=killer.name?.slice(0,1)||"?";image.hidden=false;image.src=killer.image||"";image.alt=killer.name}else{portrait.classList.add("mystery");portrait.classList.remove("portrait-error");fallback.textContent="?";image.hidden=false;image.removeAttribute("src");image.alt=""}}
function randomIndex(max){const values=new Uint32Array(1),limit=0xffffffff-(0xffffffff%max);do{crypto.getRandomValues(values)}while(values[0]>=limit);return values[0]%max}
function enabledKillers(){const ids=state.settings?.enabledKillerIds||[];return window.FOG_KILLERS.filter(killer=>ids.includes(killer.id))}
function wheelKillers(){const killers=enabledKillers(),cooldown=Math.max(0,Number(state.settings?.wheelCooldown)||0),blocked=new Set((state.randomizer?.killerHistory||[]).slice(-cooldown));if(!cooldown)return killers;const available=killers.filter(killer=>!blocked.has(killer.id));return available.length?available:killers}
function drawWheel(){const canvas=$("#overlayWheel"),context=canvas.getContext("2d"),killers=wheelKillers(),size=760,center=size/2,radius=center-15;context.clearRect(0,0,size,size);if(!killers.length){context.beginPath();context.arc(center,center,radius,0,Math.PI*2);context.fillStyle="#292a30";context.fill();return}const arc=Math.PI*2/killers.length;killers.forEach((killer,index)=>{const start=rotation+index*arc-Math.PI/2;context.beginPath();context.moveTo(center,center);context.arc(center,center,radius,start,start+arc);context.closePath();context.fillStyle=colors[index%colors.length];context.fill();context.strokeStyle="rgba(255,255,255,.12)";context.lineWidth=1.5;context.stroke();context.save();context.translate(center,center);context.rotate(start+arc/2);context.fillStyle="#f0ebe6";context.font=`${killers.length>35?16:18}px Segoe UI`;context.textAlign="right";context.textBaseline="middle";context.fillText(killer.name.toUpperCase().slice(0,15),radius-19,0);context.restore()});context.beginPath();context.arc(center,center,radius,0,Math.PI*2);context.strokeStyle="#aaa39e";context.lineWidth=4;context.stroke()}
function applyStoredState(value){state=value||state;selectedKiller=state.randomizer?.killer||null;selectedPerks=[...(state.randomizer?.perks||[])];perkLocks=[...(state.randomizer?.perkLocks||[false,false,false,false])];while(perkLocks.length<4)perkLocks.push(false);showKillerPortrait(selectedKiller);$("#overlayResult").textContent=selectedKiller?.name||"Крути колесо";$("#overlayPick").disabled=!selectedKiller;$("#overlayAgain").disabled=!selectedKiller;$("#overlayStatus").textContent=selectedKiller?"Результат перенесен из большого окна. Можно выбрать убийцу в DBD.":"Прокрутите колесо здесь или сохраните убийцу в большом окне.";renderPerks();drawWheel()}
function spin(){if(spinning)return;const killers=wheelKillers();if(!killers.length){$("#overlayStatus").textContent="Включите хотя бы одного убийцу в настройках большого окна.";return}const winner=randomIndex(killers.length),arc=Math.PI*2/killers.length,start=rotation,normalized=((start%(Math.PI*2))+Math.PI*2)%(Math.PI*2),target=-winner*arc-arc/2,delta=((target-normalized)%(Math.PI*2)+Math.PI*2)%(Math.PI*2)+(7+randomIndex(3))*Math.PI*2,duration=4000,started=performance.now();spinning=true;selectedKiller=null;showKillerPortrait(null);$(".overlay-shell").classList.add("busy");$("#overlaySpin").disabled=true;$("#overlayPick").disabled=true;$("#overlayAgain").disabled=true;$("#overlayResult").textContent="Колесо решает…";function frame(now){const progress=Math.min(1,(now-started)/duration),eased=1-Math.pow(1-progress,4);rotation=start+delta*eased;drawWheel();if(progress<1)requestAnimationFrame(frame);else{rotation=target;drawWheel();spinning=false;selectedKiller=killers[winner];showKillerPortrait(selectedKiller);$(".overlay-shell").classList.remove("busy");$("#overlaySpin").disabled=false;$("#overlayPick").disabled=false;$("#overlayAgain").disabled=false;$("#overlayResult").textContent=selectedKiller.name;$("#overlayStatus").textContent=state.settings?.automationEnabled?"Автовыбор настроен — можно выбрать убийцу.":"Убийца выбран. Автовыбор настраивается в большом окне.";const killerHistory=[...(state.randomizer?.killerHistory||[]),selectedKiller.id].slice(-50);window.fogAPI.saveRandomizer({killer:selectedKiller,killerHistory}).then(applyStoredState)}}requestAnimationFrame(frame)}
async function selectInGame(){if(!selectedKiller)return;const button=$("#overlayPick"),settings=state.settings||{};button.disabled=true;$("#overlayStatus").textContent="Выбираю убийцу в Dead by Daylight…";try{await window.fogAPI.selectKiller({killer:selectedKiller,searchPoint:settings.searchPoint,resultPoint:settings.resultPoint});$("#overlayStatus").textContent="Убийца выбран. При необходимости можно повторить."}catch(error){$("#overlayStatus").textContent=String(error.message||"Не удалось выбрать убийцу").replace(/^Error invoking remote method '[^']+': Error:\s*/,"")}finally{button.disabled=false}}
function knownKillerPerks(){const result=new Map();for(const match of state.matches||[])for(const person of [match.player,...(match.participants||[])])if(person?.role==="killer")for(const perk of person.perks||[]){const name=String(perk?.name||"").trim();if(name&&!result.has(name.toLocaleLowerCase("ru-RU")))result.set(name.toLocaleLowerCase("ru-RU"),{id:perk.id||name,name,image:perk.image||""})}return [...result.values()]}
function rerollPerks(){const catalog=knownKillerPerks();if(catalog.length<4){$("#overlayPerkStatus").textContent="В истории пока найдено меньше четырех перков убийцы.";return}const used=new Set(selectedPerks.filter((_,index)=>perkLocks[index]).map(perk=>perk.name.toLocaleLowerCase("ru-RU"))),next=[...selectedPerks];for(let index=0;index<4;index++){if(perkLocks[index]&&next[index])continue;const available=catalog.filter(perk=>!used.has(perk.name.toLocaleLowerCase("ru-RU"))),perk=available[randomIndex(available.length)];next[index]=perk;used.add(perk.name.toLocaleLowerCase("ru-RU"))}selectedPerks=next;window.fogAPI.saveRandomizer({perks:selectedPerks,perkLocks}).then(applyStoredState)}
function renderPerks(){$("#overlayPerkSlots").innerHTML=[0,1,2,3].map(index=>{const perk=selectedPerks[index],locked=perkLocks[index];return `<button type="button" data-overlay-lock="${index}" class="${locked?"locked":""}" title="${perk?.name||"Пустой слот"}">${perk?.image?`<img src="${perk.image}" alt="${perk.name}">`:'<span>?</span>'}<i>${locked?"🔒":"🔓"}</i></button>`}).join("");$$('[data-overlay-lock]').forEach(button=>button.onclick=()=>{const index=Number(button.dataset.overlayLock);if(!selectedPerks[index])return;perkLocks[index]=!perkLocks[index];window.fogAPI.saveRandomizer({perkLocks}).then(applyStoredState)});$("#overlayPickPerks").disabled=selectedPerks.filter(Boolean).length!==4}
async function selectPerks(){const settings=state.settings||{},button=$("#overlayPickPerks");button.disabled=true;$("#overlayPerkStatus").textContent="Выбираю четыре перка…";try{await window.fogAPI.selectPerks({perks:selectedPerks,slotPoints:[settings.perkSlot1Point,settings.perkSlot2Point,settings.perkSlot3Point,settings.perkSlot4Point],searchPoint:settings.perkSearchPoint,resultPoint:settings.perkResultPoint});$("#overlayPerkStatus").textContent="Перки выбраны. При необходимости можно повторить."}catch(error){$("#overlayPerkStatus").textContent=String(error.message||"Не удалось выбрать перки").replace(/^Error invoking remote method '[^']+': Error:\s*/,"")}finally{button.disabled=selectedPerks.filter(Boolean).length!==4}}
$("#closeOverlay").onclick=()=>window.fogAPI.hideOverlay();$("#overlaySpin").onclick=spin;$("#overlayAgain").onclick=spin;$("#overlayPick").onclick=selectInGame;$("#overlayRerollPerks").onclick=rerollPerks;$("#overlayPickPerks").onclick=selectPerks;
$$('[data-overlay-tab]').forEach(button=>button.onclick=()=>{$$('[data-overlay-tab]').forEach(item=>item.classList.toggle("active",item===button));const perks=button.dataset.overlayTab==="perks";$("#overlayKillerPanel").hidden=perks;$("#overlayPerkPanel").hidden=!perks});
window.addEventListener("keydown",event=>{if(event.code==="Space"&&!$("#overlayKillerPanel").hidden){event.preventDefault();spin()}if(event.code==="Escape")window.fogAPI.hideOverlay()});window.fogAPI.onOverlayShown(applyStoredState);window.fogAPI.onRandomizerUpdated(applyStoredState);(async()=>applyStoredState(await window.fogAPI.getData()))();
