const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
let state={settings:{},randomizer:{}},selectedKiller=null,selectedPerks=[],perkLocks=[false,false,false,false],perkCatalog=[],perkSpinning=false,rotation=0,spinning=false;
const colors=["#8c2229","#292a30","#641c22","#34353c","#a12830","#25262c"];
const perkNameAliases={
  Dying_Light:"Угасающий свет",DyingLight:"Угасающий свет",DecisiveStrike:"Решающий удар",ObjectOfObsession:"Объект одержимости",
  "Смотри, они бегут":"Поиграть со своей жертвой","Пусть ждут":"Оставьте лучшее напоследок","Истребление слабых":"Угасающий свет",
  "Все средства хороши":"Мертвая хватка","Порча: шут судьбы":"Порча: игрушка","Секущий крюк: сочащиеся раны":"Секущий крюк: дар боли","Секущий крюк «Пучина ярости»":"Секущий крюк: пучина ярости"
};
const perkDisplayName=perk=>perkNameAliases[String(perk?.id||"")]||perkNameAliases[String(perk?.name||"")]||String(perk?.name||"");
const isRealKillerPerk=perk=>{const name=perkDisplayName(perk).trim().toLocaleLowerCase("ru-RU").replace(/ё/g,"е");return Boolean(name)&&!["навыки убийц","навыки убийцы","умения убийц","умения убийцы"].includes(name)&&!/\(класс\)$/.test(name)};
const portraitFogStates=new WeakMap();
function fogWave(position,time,seed){return Math.sin(position*.082+time*.68+seed)*.5+Math.sin(position*.037-time*.46+seed*1.8)*.31+Math.sin(position*.151+time*.29+seed*.61)*.19}
function drawFogBand(ctx,width,height,side,time,seed,layer){const vertical=side==="left"||side==="right",length=vertical?height:width,cross=vertical?width:height,base=[.145,.112,.083][layer],variance=[.028,.023,.018][layer],alpha=[.2,.16,.12][layer]*(side==="top"?.72:side==="bottom"?.88:1),depthAt=position=>cross*Math.max(.045,base+fogWave(position,time,seed+layer*2.4)*variance);ctx.beginPath();if(side==="left"){ctx.moveTo(0,0);ctx.lineTo(0,height);for(let p=length;p>=0;p-=3)ctx.lineTo(depthAt(p),p)}else if(side==="right"){ctx.moveTo(width,0);ctx.lineTo(width,height);for(let p=length;p>=0;p-=3)ctx.lineTo(width-depthAt(p),p)}else if(side==="top"){ctx.moveTo(0,0);ctx.lineTo(width,0);for(let p=length;p>=0;p-=3)ctx.lineTo(p,depthAt(p))}else{ctx.moveTo(0,height);ctx.lineTo(width,height);for(let p=length;p>=0;p-=3)ctx.lineTo(p,height-depthAt(p))}ctx.closePath();const fade=Math.min(cross*.22,Math.max(...[.145,.112,.083])*cross*1.55),gradient=side==="left"?ctx.createLinearGradient(0,0,fade,0):side==="right"?ctx.createLinearGradient(width,0,width-fade,0):side==="top"?ctx.createLinearGradient(0,0,0,fade):ctx.createLinearGradient(0,height,0,height-fade);gradient.addColorStop(0,`rgba(229,232,231,${alpha})`);gradient.addColorStop(.26,`rgba(201,206,205,${alpha*.72})`);gradient.addColorStop(.56,`rgba(168,175,176,${alpha*.31})`);gradient.addColorStop(.82,`rgba(144,152,154,${alpha*.08})`);gradient.addColorStop(1,"rgba(128,136,139,0)");ctx.fillStyle=gradient;ctx.fill()}
function drawPortraitFog(fog,now){const {canvas,ctx,seed}=fog,width=canvas.width,height=canvas.height,time=now/1000;ctx.clearRect(0,0,width,height);ctx.save();for(let layer=0;layer<3;layer++){drawFogBand(ctx,width,height,"left",time,seed,layer);drawFogBand(ctx,width,height,"right",time,seed+5.2,layer);drawFogBand(ctx,width,height,"bottom",time,seed+9.1,layer);drawFogBand(ctx,width,height,"top",time,seed+13.4,layer)}ctx.globalCompositeOperation="screen";for(let i=0;i<6;i++){const right=i%2===1,cy=((i+.4)*height/6+Math.sin(time*.54+i*1.7)*8+height)%height,cx=right?width:0,radius=width*(.105+(i%3)*.014),gradient=ctx.createRadialGradient(cx,cy,0,cx,cy,radius);gradient.addColorStop(0,"rgba(235,237,235,.075)");gradient.addColorStop(.48,"rgba(187,193,192,.035)");gradient.addColorStop(1,"rgba(147,154,157,0)");ctx.fillStyle=gradient;ctx.fillRect(right?width-radius:0,cy-radius,radius,radius*2)}ctx.restore()}
function setPortraitFogActive(portrait,active){if(!portrait)return;let fog=portraitFogStates.get(portrait);if(!fog){const canvas=portrait.querySelector(".portrait-fog-canvas");if(!canvas)return;fog={canvas,ctx:canvas.getContext("2d",{alpha:true}),seed:Math.random()*20,running:false,lastPaint:0};portraitFogStates.set(portrait,fog)}fog.active=Boolean(active);if(!fog.active){fog.ctx.clearRect(0,0,fog.canvas.width,fog.canvas.height);fog.running=false;return}if(fog.running)return;fog.running=true;const frame=now=>{if(!fog.active||document.hidden||!portrait.isConnected){fog.running=false;return}if(now-fog.lastPaint>=50){fog.lastPaint=now;drawPortraitFog(fog,now)}requestAnimationFrame(frame)};requestAnimationFrame(frame)}
function showKillerPortrait(killer){let portrait=document.querySelector(".overlay-result-portrait");if(!portrait){portrait=document.createElement("div");portrait.className="overlay-result-portrait mystery";portrait.innerHTML='<span>?</span><img alt=""><canvas class="portrait-fog-canvas" width="64" height="70" aria-hidden="true"></canvas>';document.querySelector(".result-panel").prepend(portrait)}const image=portrait.querySelector("img"),fallback=portrait.querySelector("span");image.onload=()=>{image.hidden=false;portrait.classList.remove("portrait-error")};image.onerror=()=>{image.hidden=true;fallback.textContent=killer?.name?.slice(0,1)||"?";portrait.classList.add("portrait-error")};if(killer){portrait.classList.remove("mystery","portrait-error");fallback.textContent=killer.name?.slice(0,1)||"?";image.hidden=false;image.src=killer.image||"";image.alt=killer.name}else{portrait.classList.add("mystery");portrait.classList.remove("portrait-error");fallback.textContent="?";image.hidden=false;image.removeAttribute("src");image.alt=""}setPortraitFogActive(portrait,Boolean(killer))}
function randomIndex(max){const values=new Uint32Array(1),limit=0xffffffff-(0xffffffff%max);do{crypto.getRandomValues(values)}while(values[0]>=limit);return values[0]%max}
function enabledKillers(){const ids=state.settings?.enabledKillerIds||[];return window.FOG_KILLERS.filter(killer=>ids.includes(killer.id))}
function wheelKillers(){const killers=enabledKillers(),cooldown=Math.max(0,Number(state.settings?.wheelCooldown)||0),blocked=new Set((state.randomizer?.killerHistory||[]).slice(-cooldown));if(!cooldown)return killers;const available=killers.filter(killer=>!blocked.has(killer.id));return available.length?available:killers}
function applyWheelRotation(){const canvas=$("#overlayWheel");canvas.style.transform=`translateZ(0) rotate(${rotation}rad)`}
function drawWheel(){const canvas=$("#overlayWheel"),context=canvas.getContext("2d",{alpha:true}),killers=wheelKillers(),size=760,center=size/2,radius=center-15,empty=!killers.length;context.clearRect(0,0,size,size);canvas.parentElement.classList.toggle("empty-wheel",empty);$("#overlaySpin").hidden=empty;if(empty){canvas.style.transform="translateZ(0)";context.beginPath();context.arc(center,center,radius,0,Math.PI*2);context.fillStyle="#292a30";context.fill();context.strokeStyle="#c7c0ba";context.lineWidth=4;context.stroke();context.fillStyle="#b8b2b6";context.font="700 20px Segoe UI";context.textAlign="center";context.textBaseline="middle";context.fillText("ВКЛЮЧИТЕ ХОТЯ БЫ ОДНОГО УБИЙЦУ",center,center);return}const arc=Math.PI*2/killers.length;killers.forEach((killer,index)=>{const start=index*arc-Math.PI/2;context.beginPath();context.moveTo(center,center);context.arc(center,center,radius,start,start+arc);context.closePath();context.fillStyle=colors[index%colors.length];context.fill();context.strokeStyle="rgba(255,255,255,.12)";context.lineWidth=1.5;context.stroke();context.save();context.translate(center,center);context.rotate(start+arc/2);context.fillStyle="#f0ebe6";context.font=`${killers.length>35?16:18}px Segoe UI`;context.textAlign="right";context.textBaseline="middle";context.fillText(killer.name.toUpperCase().slice(0,15),radius-19,0);context.restore()});context.beginPath();context.arc(center,center,radius,0,Math.PI*2);context.strokeStyle="#aaa39e";context.lineWidth=4;context.stroke();applyWheelRotation()}
function applyStoredState(value){state=value||state;selectedKiller=state.randomizer?.killer||null;selectedPerks=[...(state.randomizer?.perks||[])].map(perk=>isRealKillerPerk(perk)?perk:null);perkLocks=[...(state.randomizer?.perkLocks||[false,false,false,false])];while(perkLocks.length<4)perkLocks.push(false);showKillerPortrait(selectedKiller);$("#overlayResult").textContent=selectedKiller?.name||"Крути колесо";$("#overlayPick").disabled=!selectedKiller;$("#overlayAgain").disabled=!selectedKiller;$("#overlayStatus").textContent=selectedKiller?"Результат перенесен из большого окна. Можно выбрать убийцу в DBD.":"Прокрутите колесо здесь или сохраните убийцу в большом окне.";renderPerks();drawWheel()}
function spin(){if(spinning)return;const killers=wheelKillers();if(!killers.length){$("#overlayStatus").textContent="Включите хотя бы одного убийцу в настройках большого окна.";return}const winner=randomIndex(killers.length),arc=Math.PI*2/killers.length,start=rotation,normalized=((start%(Math.PI*2))+Math.PI*2)%(Math.PI*2),target=-winner*arc-arc/2,delta=((target-normalized)%(Math.PI*2)+Math.PI*2)%(Math.PI*2)+(7+randomIndex(3))*Math.PI*2,duration=4000,started=performance.now();spinning=true;selectedKiller=null;showKillerPortrait(null);$(".overlay-shell").classList.add("busy");$("#overlaySpin").disabled=true;$("#overlayPick").disabled=true;$("#overlayAgain").disabled=true;$("#overlayResult").textContent="Колесо решает…";function frame(now){const progress=Math.min(1,(now-started)/duration),eased=1-Math.pow(1-progress,4);rotation=start+delta*eased;applyWheelRotation();if(progress<1)requestAnimationFrame(frame);else{rotation=target;applyWheelRotation();spinning=false;selectedKiller=killers[winner];showKillerPortrait(selectedKiller);$(".overlay-shell").classList.remove("busy");$("#overlaySpin").disabled=false;$("#overlayPick").disabled=false;$("#overlayAgain").disabled=false;$("#overlayResult").textContent=selectedKiller.name;$("#overlayStatus").textContent=state.settings?.automationEnabled?"Автовыбор настроен — можно выбрать убийцу.":"Убийца выбран. Автовыбор настраивается в большом окне.";const killerHistory=[...(state.randomizer?.killerHistory||[]),selectedKiller.id].slice(-50);window.fogAPI.saveRandomizer({killer:selectedKiller,killerHistory}).then(applyStoredState)}}requestAnimationFrame(frame)}
async function selectInGame(){if(!selectedKiller)return;const button=$("#overlayPick"),settings=state.settings||{};button.disabled=true;$("#overlayStatus").textContent="Выбираю убийцу в Dead by Daylight…";try{await window.fogAPI.selectKiller({killer:selectedKiller,searchPoint:settings.searchPoint,resultPoint:settings.resultPoint});$("#overlayStatus").textContent="Убийца выбран. При необходимости можно повторить."}catch(error){$("#overlayStatus").textContent=String(error.message||"Не удалось выбрать убийцу").replace(/^Error invoking remote method '[^']+': Error:\s*/,"")}finally{button.disabled=false}}
function knownKillerPerks(){const result=new Map();for(const match of state.matches||[])for(const person of [match.player,...(match.participants||[])])if(person?.role==="killer")for(const perk of person.perks||[]){const name=perkDisplayName(perk).trim();if(name&&!result.has(name.toLocaleLowerCase("ru-RU")))result.set(name.toLocaleLowerCase("ru-RU"),{id:perk.id||name,name,image:perk.image||""})}return [...result.values()]}
function allKillerPerks(){const result=new Map();for(const perk of [...perkCatalog,...knownKillerPerks()]){const key=String(perk?.name||"").trim().toLocaleLowerCase("ru-RU");if(!key)continue;const previous=result.get(key);result.set(key,previous?{...perk,...previous,image:previous.image||perk.image||""}:perk)}return [...result.values()]}
function enabledPerks(){const all=allKillerPerks(),ids=new Set(state.settings?.enabledPerkIds||[]);return state.settings?.perkFilterInitialized?all.filter(perk=>ids.has(String(perk.id))):all}
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function preloadPerkImages(perks){return Promise.all([...new Set(perks.map(perk=>perk?.image).filter(Boolean))].map(url=>new Promise(resolve=>{const image=new Image(),done=()=>resolve();image.onload=done;image.onerror=done;image.src=url;setTimeout(done,3500)})))}
function setOverlayPerkVisual(index,perk,rolling=false){const slot=document.querySelector(`[data-overlay-lock="${index}"]`);if(!slot)return;slot.classList.toggle("rolling",rolling);slot.title=perk?.name||"Пустой слот";const old=slot.querySelector("img,span");old?.remove();slot.insertAdjacentHTML("afterbegin",perk?.image?`<img src="${perk.image}" alt="${perk.name}">`:'<span>?</span>')}
async function rerollPerks(){if(perkSpinning)return;const catalog=enabledPerks();if(catalog.length<4){$("#overlayPerkStatus").textContent="Включите хотя бы четыре перка в настройках большого окна.";return}const unlocked=[0,1,2,3].filter(index=>!perkLocks[index]||!selectedPerks[index]);if(!unlocked.length){$("#overlayPerkStatus").textContent="Все четыре перка закреплены.";return}const cooldown=Math.max(0,Number(state.settings?.perkCooldown)||0),history=(state.randomizer?.perkHistory||[]).filter(Array.isArray),blocked=new Set(history.slice(-cooldown).flat().map(String)),used=new Set(selectedPerks.filter((_,index)=>perkLocks[index]).map(perk=>String(perk.id))),next=[...selectedPerks],rolled=[];for(const index of unlocked){let available=catalog.filter(perk=>!used.has(String(perk.id))&&!blocked.has(String(perk.id)));if(!available.length)available=catalog.filter(perk=>!used.has(String(perk.id)));const perk=available[randomIndex(available.length)];next[index]=perk;used.add(String(perk.id));rolled.push(String(perk.id))}const sequences=new Map(unlocked.map((index,offset)=>{const sequence=[];for(let step=0;step<9+offset;step++)sequence.push(catalog[randomIndex(catalog.length)]);sequence.push(next[index]);return[index,sequence]}));perkSpinning=true;renderPerks();$("#overlayPerkStatus").textContent="Загружаю изображения перков…";await preloadPerkImages([...sequences.values()].flat());$("#overlayPerkStatus").textContent="Перки вращаются…";await Promise.all(unlocked.map(async index=>{const sequence=sequences.get(index);for(let step=0;step<sequence.length;step++){setOverlayPerkVisual(index,sequence[step],true);await wait(45+step*step*1.4)}setOverlayPerkVisual(index,next[index],false)}));selectedPerks=next;const perkHistory=[...history,rolled].slice(-50);perkSpinning=false;state=await window.fogAPI.saveRandomizer({perks:selectedPerks,perkLocks,perkHistory});applyStoredState(state);$("#overlayPerkStatus").textContent="Сборка готова. Закрепите перки или выберите их в DBD."}
function renderPerks(){$("#overlayPerkSlots").innerHTML=[0,1,2,3].map(index=>{const perk=selectedPerks[index],locked=perkLocks[index];return `<button type="button" data-overlay-lock="${index}" class="${locked?"locked":""}" title="${perk?.name||"Пустой слот"}" ${perkSpinning?"disabled":""}>${perk?.image?`<img src="${perk.image}" alt="${perk.name}">`:'<span>?</span>'}<i>${locked?"🔒":"🔓"}</i></button>`}).join("");$$('[data-overlay-lock]').forEach(button=>button.onclick=()=>{const index=Number(button.dataset.overlayLock);if(!selectedPerks[index]||perkSpinning)return;perkLocks[index]=!perkLocks[index];window.fogAPI.saveRandomizer({perkLocks}).then(applyStoredState)});$("#overlayPickPerks").disabled=perkSpinning||selectedPerks.filter(Boolean).length!==4||perkLocks.every(Boolean);$("#overlayRerollPerks").disabled=perkSpinning}
async function selectPerks(){const settings=state.settings||{},button=$("#overlayPickPerks"),editable=selectedPerks.map((perk,index)=>perk&&!perkLocks[index]?index:null).filter(index=>index!==null);if(!editable.length){$("#overlayPerkStatus").textContent="Все четыре перка закреплены — выбирать в DBD нечего.";return}button.disabled=true;$("#overlayPerkStatus").textContent=`Выбираю ${editable.length===1?"измененный перк":`${editable.length} измененных перка`}…`;try{await window.fogAPI.selectPerks({perks:selectedPerks,perkLocks,slotPoints:[settings.perkSlot1Point,settings.perkSlot2Point,settings.perkSlot3Point,settings.perkSlot4Point],searchPoint:settings.perkSearchPoint,resultPoint:settings.perkResultPoint,clearPoint:settings.perkClearPoint});$("#overlayPerkStatus").textContent="Незакрепленные перки выбраны. При необходимости можно повторить."}catch(error){$("#overlayPerkStatus").textContent=String(error.message||"Не удалось выбрать перки").replace(/^Error invoking remote method '[^']+': Error:\s*/,"")}finally{button.disabled=selectedPerks.filter(Boolean).length!==4||perkLocks.every(Boolean)}}
$(".overlay-shell").addEventListener("mouseenter",()=>window.fogAPI.setOverlayHover(true));$(".overlay-shell").addEventListener("mouseleave",()=>window.fogAPI.setOverlayHover(false));$("#closeOverlay").onclick=()=>window.fogAPI.hideOverlay();$("#overlaySpin").onclick=spin;$("#overlayAgain").onclick=spin;$("#overlayPick").onclick=selectInGame;$("#overlayRerollPerks").onclick=rerollPerks;$("#overlayPickPerks").onclick=selectPerks;
$$('[data-overlay-tab]').forEach(button=>button.onclick=()=>{$$('[data-overlay-tab]').forEach(item=>item.classList.toggle("active",item===button));const perks=button.dataset.overlayTab==="perks";$("#overlayKillerPanel").hidden=perks;$("#overlayPerkPanel").hidden=!perks});
window.addEventListener("keydown",event=>{if(event.code==="Space"&&!$("#overlayKillerPanel").hidden){event.preventDefault();spin()}if(event.code==="Escape")window.fogAPI.hideOverlay()});window.fogAPI.onOverlayShown(value=>{applyStoredState(value);perkCatalog=value.perkCatalog?.items||perkCatalog});window.fogAPI.onRandomizerUpdated(applyStoredState);(async()=>{applyStoredState(await window.fogAPI.getData());try{const result=await window.fogAPI.getKillerPerks();perkCatalog=result.items||[];if(result.data)applyStoredState(result.data)}catch{perkCatalog=state.perkCatalog?.items||[]}})();
